In [ ]:
# Install Playwright (uncomment and run if not installed)
# !python -m pip install playwright
# !python -m playwright install chromium

OUTPUT_PLAYWRIGHT_TEST = '/workspace/cars24_playwright_test.csv'  # target path; may not be writable
FALLBACK_OUTPUT = '~/cars24_playwright_test.csv'
HTML_SNAPSHOT_PATH = '/workspace/cars24_hyderabad_snapshot.html'
FALLBACK_HTML_SNAPSHOT = '~/cars24_hyderabad_snapshot.html'
CITY = 'Hyderabad'
CITY_URL = 'https://www.cars24.com/buy-used-cars-hyderabad/'
MAX_LISTINGS = 20
REQUEST_DELAY = 2

In [ ]:
from playwright.sync_api import sync_playwright, TimeoutError as PlaywrightTimeoutError
from bs4 import BeautifulSoup
import pandas as pd
import time, re, os, datetime

def detect_blocking(page_content):
    s = page_content.lower()
    keys = ['captcha','access denied','are you human','verify','unusual traffic','bot verification','blocked']
    for k in keys:
        if k in s:
            return True, k
    return False, None

# Try multiple selector strategies to locate listing cards on the rendered page
CARD_SELECTORS = [
    'a[href*=
]',
    'a[href*=
]',
    'div[data-listing-id] a',
    'article a[href*=
]',
    'a[class*=ListingCard], a[class*=listing]'
: 
,
: {
: 

: [
,
,
,
,
,
,
,
,
,
,
,

In [1]:
import pandas as pd

df = pd.read_csv("cars24_playwright_test.csv")

print("Total records:", len(df))
print("Columns:", df.columns.tolist())

print("\nFuel types:")
print(df["fuel_type"].value_counts(dropna=False))

print("\nTransmissions:")
print(df["transmission"].value_counts(dropna=False))

print("\nUnique URLs:", df["listing_url"].nunique())
print("Duplicate URLs:", df["listing_url"].duplicated().sum())

display(df.head(20))

Total records: 20
Columns: ['listing_url', 'listing_id', 'car_name', 'price', 'manufacturing_year', 'km_driven', 'fuel_type', 'transmission', 'brand', 'model', 'variant', 'location', 'city', 'state']

Fuel types:
fuel_type
Petrol    20
Name: count, dtype: int64

Transmissions:
transmission
Automatic    20
Name: count, dtype: int64

Unique URLs: 20
Duplicate URLs: 0

,listing_url,listing_id,car_name,price,manufacturing_year,km_driven,fuel_type,transmission,brand,model,variant,location,city,state
0,https://www.cars24.com/buy-used-nissan-kicks-c...,NaN,5 Second Hand Nissan Kicks in Hyderabad,"EMI ₹11,925/m*",2019,"1,18,342",Petrol,Automatic,5,5 Second,Hand Nissan,Hyderabad,Hyderabad,NaN
1,https://www.cars24.com/buy-used-sunroof-cars-h...,NaN,535 Used Sunroof cars in Hyderabad,535 Second Hand Sunroof Cars in Hyderabad | Us...,2022,"54,649",Petrol,Automatic,535,535 Used,Sunroof cars,Hyderabad,Hyderabad,NaN
2,https://www.cars24.com/buy-used-honda-amaze-ca...,NaN,38 Second Hand Honda Amaze in Hyderabad,₹2.50 lakh - ₹3.60 lakh,2013,46,Petrol,Automatic,38,38 Second,Hand Honda,Hyderabad,Hyderabad,NaN
3,https://www.cars24.com/buy-used-mahindra-xuv50...,NaN,32 Second Hand Mahindra XUV500 in Hyderabad,"EMI ₹15,952/m*",2011,1,Petrol,Automatic,32,32 Second,Hand Mahindra,Hyderabad,Hyderabad,NaN
4,https://www.cars24.com/buy-used-renault-kwid-2...,NaN,2020Renault KwidCLIMBER 1.0 (O),"₹6,371/mo",2020,"33,425",Petrol,Automatic,2020Renault,2020Renault KwidCLIMBER,1.0 (O),"Bachupally, Hyderabad",Hyderabad,NaN
5,https://www.cars24.com/buy-used-maruti-s-press...,NaN,7 Second Hand Maruti S PRESSO in Hyderabad,₹3.70 lakh - ₹4.00 lakh,2020,21,Petrol,Automatic,7,7 Second,Hand Maruti,Hyderabad,Hyderabad,NaN
6,https://www.cars24.com/buy-used-audi-a4-cars-h...,NaN,4 Second Hand Audi A4 in Hyderabad,₹6.70 lakh - ₹14.90 lakh,2015,"1,06,735",Petrol,Automatic,4,4 Second,Hand Audi,Hyderabad,Hyderabad,NaN
7,https://www.cars24.com/buy-used-bmw-5-series-c...,NaN,2 Second Hand BMW 5 Series in Hyderabad,₹10.50 lakh - ₹29.00 lakh,2012,"75,696",Petrol,Automatic,2,2 Second,Hand BMW,Hyderabad,Hyderabad,NaN
8,https://www.cars24.com/buy-used-skoda-karoq-ca...,NaN,2 Second Hand Skoda Karoq in Hyderabad,"EMI ₹22,784/m*",2020,"1,05,516",Petrol,Automatic,2,2 Second,Hand Skoda,Hyderabad,Hyderabad,NaN
9,https://www.cars24.com/buy-used-ford-figo-cars...,NaN,21 Second Hand Ford Figo in Hyderabad,₹1.00 lakh - ₹1.36 lakh,2011,20,Petrol,Automatic,21,21 Second,Hand Ford,Hyderabad,Hyderabad,NaN
10,https://www.cars24.com/buy-used-manual-cars-hy...,NaN,1527 Used Manual cars in Hyderabad,1527 Second Hand Manual Cars in Hyderabad | Us...,2024,"15,400",Petrol,Automatic,1527,1527 Used,Manual cars,Hyderabad,Hyderabad,NaN
11,https://www.cars24.com/buy-used-mahindra-cars-...,NaN,141 Used Mahindra cars in Hyderabad,141 Mahindra Used Cars in Hyderabad | Second H...,2022,"45,924",Petrol,Automatic,141,141 Used,Mahindra cars,Hyderabad,Hyderabad,NaN
12,https://www.cars24.com/buy-used-jaguar-cars-hy...,NaN,4 Used Jaguar cars in Hyderabad,"Used Jaguar Cars in Hyderabad, Second Hand Jag...",2015,"94,140",Petrol,Automatic,4,4 Used,Jaguar cars,Hyderabad,Hyderabad,NaN
13,https://www.cars24.com/buy-used-volkswagen-tai...,NaN,14 Second Hand Volkswagen TAIGUN in Hyderabad,₹8.09 lakh - ₹10.50 lakh,2021,19,Petrol,Automatic,14,14 Second,Hand Volkswagen,Hyderabad,Hyderabad,NaN
14,https://www.cars24.com/buy-used-honda-wr-v-car...,NaN,12 Second Hand Honda WR-V in Hyderabad,₹5.25 lakh - ₹7.10 lakh,2017,5,Petrol,Automatic,12,12 Second,Hand Honda,Hyderabad,Hyderabad,NaN
15,https://www.cars24.com/buy-used-toyota-urban-c...,NaN,1 Second Hand Toyota URBAN CRUISER in Hyderabad,"EMI ₹13,698/m*",2021,"60,335",Petrol,Automatic,1,1 Second,Hand Toyota,Hyderabad,Hyderabad,NaN
16,https://www.cars24.com/buy-used-mahindra-xylo-...,NaN,2 Second Hand Mahindra Xylo in Hyderabad,"EMI ₹7,341/m*",2017,"2,39,240",Petrol,Automatic,2,2 Second,Hand Mahindra,Hyderabad,Hyderabad,NaN
17,https://www.cars24.com/buy-used-ford-cars-hyde...,NaN,72 Used Ford cars in Hyderabad,72 Ford Used Cars in Hyderabad | Second Hand F...,2019,"78,135",Petrol,Automatic,72,72 Used,Ford cars,Hyderabad,Hyderabad,NaN
18,https://www.cars24.com/buy-used-hyundai-venue-...,NaN,2 Second Hand Hyundai VENUE N LINE in Hyderabad,"EMI ₹20,547/m*",2024,"1,304",Petrol,Automatic,2,2 Second,Hand Hyundai,Hyderabad,Hyderabad,NaN
19,https://www.cars24.com/buy-used-jeep-compass-c...,NaN,17 Second Hand Jeep Compass in Hyderabad,"EMI ₹13,392/m*",2018,"46,292",Petrol,Automatic,17,17 Second,Hand Jeep,Hyderabad,Hyderabad,NaN

In [2]:
print("Sample scraped data:")

display(
    df[
        [
            "listing_url",
            "car_name",
            "price",
            "manufacturing_year",
            "km_driven",
            "fuel_type",
            "transmission",
            "brand",
            "model",
            "variant",
            "location",
            "city",
            "state"
        ]
    ].head(20)
)

Sample scraped data:

,listing_url,car_name,price,manufacturing_year,km_driven,fuel_type,transmission,brand,model,variant,location,city,state
0,https://www.cars24.com/buy-used-nissan-kicks-c...,5 Second Hand Nissan Kicks in Hyderabad,"EMI ₹11,925/m*",2019,"1,18,342",Petrol,Automatic,5,5 Second,Hand Nissan,Hyderabad,Hyderabad,NaN
1,https://www.cars24.com/buy-used-sunroof-cars-h...,535 Used Sunroof cars in Hyderabad,535 Second Hand Sunroof Cars in Hyderabad | Us...,2022,"54,649",Petrol,Automatic,535,535 Used,Sunroof cars,Hyderabad,Hyderabad,NaN
2,https://www.cars24.com/buy-used-honda-amaze-ca...,38 Second Hand Honda Amaze in Hyderabad,₹2.50 lakh - ₹3.60 lakh,2013,46,Petrol,Automatic,38,38 Second,Hand Honda,Hyderabad,Hyderabad,NaN
3,https://www.cars24.com/buy-used-mahindra-xuv50...,32 Second Hand Mahindra XUV500 in Hyderabad,"EMI ₹15,952/m*",2011,1,Petrol,Automatic,32,32 Second,Hand Mahindra,Hyderabad,Hyderabad,NaN
4,https://www.cars24.com/buy-used-renault-kwid-2...,2020Renault KwidCLIMBER 1.0 (O),"₹6,371/mo",2020,"33,425",Petrol,Automatic,2020Renault,2020Renault KwidCLIMBER,1.0 (O),"Bachupally, Hyderabad",Hyderabad,NaN
5,https://www.cars24.com/buy-used-maruti-s-press...,7 Second Hand Maruti S PRESSO in Hyderabad,₹3.70 lakh - ₹4.00 lakh,2020,21,Petrol,Automatic,7,7 Second,Hand Maruti,Hyderabad,Hyderabad,NaN
6,https://www.cars24.com/buy-used-audi-a4-cars-h...,4 Second Hand Audi A4 in Hyderabad,₹6.70 lakh - ₹14.90 lakh,2015,"1,06,735",Petrol,Automatic,4,4 Second,Hand Audi,Hyderabad,Hyderabad,NaN
7,https://www.cars24.com/buy-used-bmw-5-series-c...,2 Second Hand BMW 5 Series in Hyderabad,₹10.50 lakh - ₹29.00 lakh,2012,"75,696",Petrol,Automatic,2,2 Second,Hand BMW,Hyderabad,Hyderabad,NaN
8,https://www.cars24.com/buy-used-skoda-karoq-ca...,2 Second Hand Skoda Karoq in Hyderabad,"EMI ₹22,784/m*",2020,"1,05,516",Petrol,Automatic,2,2 Second,Hand Skoda,Hyderabad,Hyderabad,NaN
9,https://www.cars24.com/buy-used-ford-figo-cars...,21 Second Hand Ford Figo in Hyderabad,₹1.00 lakh - ₹1.36 lakh,2011,20,Petrol,Automatic,21,21 Second,Hand Ford,Hyderabad,Hyderabad,NaN
10,https://www.cars24.com/buy-used-manual-cars-hy...,1527 Used Manual cars in Hyderabad,1527 Second Hand Manual Cars in Hyderabad | Us...,2024,"15,400",Petrol,Automatic,1527,1527 Used,Manual cars,Hyderabad,Hyderabad,NaN
11,https://www.cars24.com/buy-used-mahindra-cars-...,141 Used Mahindra cars in Hyderabad,141 Mahindra Used Cars in Hyderabad | Second H...,2022,"45,924",Petrol,Automatic,141,141 Used,Mahindra cars,Hyderabad,Hyderabad,NaN
12,https://www.cars24.com/buy-used-jaguar-cars-hy...,4 Used Jaguar cars in Hyderabad,"Used Jaguar Cars in Hyderabad, Second Hand Jag...",2015,"94,140",Petrol,Automatic,4,4 Used,Jaguar cars,Hyderabad,Hyderabad,NaN
13,https://www.cars24.com/buy-used-volkswagen-tai...,14 Second Hand Volkswagen TAIGUN in Hyderabad,₹8.09 lakh - ₹10.50 lakh,2021,19,Petrol,Automatic,14,14 Second,Hand Volkswagen,Hyderabad,Hyderabad,NaN
14,https://www.cars24.com/buy-used-honda-wr-v-car...,12 Second Hand Honda WR-V in Hyderabad,₹5.25 lakh - ₹7.10 lakh,2017,5,Petrol,Automatic,12,12 Second,Hand Honda,Hyderabad,Hyderabad,NaN
15,https://www.cars24.com/buy-used-toyota-urban-c...,1 Second Hand Toyota URBAN CRUISER in Hyderabad,"EMI ₹13,698/m*",2021,"60,335",Petrol,Automatic,1,1 Second,Hand Toyota,Hyderabad,Hyderabad,NaN
16,https://www.cars24.com/buy-used-mahindra-xylo-...,2 Second Hand Mahindra Xylo in Hyderabad,"EMI ₹7,341/m*",2017,"2,39,240",Petrol,Automatic,2,2 Second,Hand Mahindra,Hyderabad,Hyderabad,NaN
17,https://www.cars24.com/buy-used-ford-cars-hyde...,72 Used Ford cars in Hyderabad,72 Ford Used Cars in Hyderabad | Second Hand F...,2019,"78,135",Petrol,Automatic,72,72 Used,Ford cars,Hyderabad,Hyderabad,NaN
18,https://www.cars24.com/buy-used-hyundai-venue-...,2 Second Hand Hyundai VENUE N LINE in Hyderabad,"EMI ₹20,547/m*",2024,"1,304",Petrol,Automatic,2,2 Second,Hand Hyundai,Hyderabad,Hyderabad,NaN
19,https://www.cars24.com/buy-used-jeep-compass-c...,17 Second Hand Jeep Compass in Hyderabad,"EMI ₹13,392/m*",2018,"46,292",Petrol,Automatic,17,17 Second,Hand Jeep,Hyderabad,Hyderabad,NaN

In [3]:
# Check which URLs were scraped
import pandas as pd

df = pd.read_csv("cars24_playwright_test.csv")

print("Total records:", len(df))

print("\nScraped URLs:")
for i, url in enumerate(df["listing_url"].head(20), 1):
    print(i, url)

print("\nURL patterns:")
print(
    df["listing_url"]
    .str.extract(r'cars24\.com/(.*?)/?$')[0]
    .head(20)
)

Total records: 20

Scraped URLs:
1 https://www.cars24.com/buy-used-nissan-kicks-cars-hyderabad/
2 https://www.cars24.com/buy-used-sunroof-cars-hyderabad/
3 https://www.cars24.com/buy-used-honda-amaze-cars-hyderabad/
4 https://www.cars24.com/buy-used-mahindra-xuv500-cars-hyderabad/
5 https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/
6 https://www.cars24.com/buy-used-maruti-s-presso-cars-hyderabad/
7 https://www.cars24.com/buy-used-audi-a4-cars-hyderabad/
8 https://www.cars24.com/buy-used-bmw-5-series-cars-hyderabad/
9 https://www.cars24.com/buy-used-skoda-karoq-cars-hyderabad/
10 https://www.cars24.com/buy-used-ford-figo-cars-hyderabad/
11 https://www.cars24.com/buy-used-manual-cars-hyderabad/
12 https://www.cars24.com/buy-used-mahindra-cars-hyderabad/
13 https://www.cars24.com/buy-used-jaguar-cars-hyderabad/
14 https://www.cars24.com/buy-used-volkswagen-taigun-cars-hyderabad/
15 https://www.cars24.com/buy-used-honda-wr-v-cars-hyderabad/
16 https://www.cars24.com/buy-used-toyota-urban-cruiser-cars-hyderabad/
17 https://www.cars24.com/buy-used-mahindra-xylo-cars-hyderabad/
18 https://www.cars24.com/buy-used-ford-cars-hyderabad/
19 https://www.cars24.com/buy-used-hyundai-venue-n-line-cars-hyderabad/
20 https://www.cars24.com/buy-used-jeep-compass-cars-hyderabad/

URL patterns:
0                  buy-used-nissan-kicks-cars-hyderabad
1                       buy-used-sunroof-cars-hyderabad
2                   buy-used-honda-amaze-cars-hyderabad
3               buy-used-mahindra-xuv500-cars-hyderabad
4     buy-used-renault-kwid-2020-cars-hyderabad-1045...
5               buy-used-maruti-s-presso-cars-hyderabad
6                       buy-used-audi-a4-cars-hyderabad
7                  buy-used-bmw-5-series-cars-hyderabad
8                   buy-used-skoda-karoq-cars-hyderabad
9                     buy-used-ford-figo-cars-hyderabad
10                       buy-used-manual-cars-hyderabad
11                     buy-used-mahindra-cars-hyderabad
12                       buy-used-jaguar-cars-hyderabad
13            buy-used-volkswagen-taigun-cars-hyderabad
14                   buy-used-honda-wr-v-cars-hyderabad
15         buy-used-toyota-urban-cruiser-cars-hyderabad
16                buy-used-mahindra-xylo-cars-hyderabad
17                         buy-used-ford-cars-hyderabad
18         buy-used-hyundai-venue-n-line-cars-hyderabad
19                 buy-used-jeep-compass-cars-hyderabad
Name: 0, dtype: str

In [4]:
import re
import pandas as pd

df = pd.read_csv("cars24_playwright_test.csv")

# Keep only URLs that look like individual Cars24 listings
# Individual listing URLs contain a numeric listing ID at the end.
pattern = r"cars24\.com/.+-hyderabad-\d+/?$"

df_individual = df[
    df["listing_url"].astype(str).str.contains(
        pattern,
        regex=True,
        case=False,
        na=False
    )
].copy()

print("Total scraped URLs:", len(df))
print("Individual listing URLs:", len(df_individual))
print("Category/filter URLs removed:", len(df) - len(df_individual))

display(df_individual)

Total scraped URLs: 20
Individual listing URLs: 1
Category/filter URLs removed: 19

,listing_url,listing_id,car_name,price,manufacturing_year,km_driven,fuel_type,transmission,brand,model,variant,location,city,state
4,https://www.cars24.com/buy-used-renault-kwid-2...,NaN,2020Renault KwidCLIMBER 1.0 (O),"₹6,371/mo",2020,"33,425",Petrol,Automatic,2020Renault,2020Renault KwidCLIMBER,1.0 (O),"Bachupally, Hyderabad",Hyderabad,NaN

In [5]:
import re
from playwright.async_api import async_playwright

url = "https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/"

async def inspect_listing():
    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page(
            viewport={"width": 1440, "height": 900}
        )

        print("Opening listing...")

        await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        await page.wait_for_timeout(5000)

        print("Title:", await page.title())

        text = await page.locator("body").inner_text()

        print("\n========== LISTING TEXT ==========\n")
        print(text[:10000])

        await browser.close()


await inspect_listing()

Opening listing...
Title: Used 2020 Renault Kwid CLIMBER 1.0 (O) Manual in Hyderabad | 33,425 Kms - Cars24

========== LISTING TEXT ==========

Hyderabad

Buy used car

Sell car

Car finance

New cars

Car services

Call us

Hello, Sign in

Account

Overview

Car inspection report

Features and specs

 Previous

Reasons to buy this car

Smart connectivity
Fuel-efficient car
GPS connectivity

Top features of this car

ABS - Anti-lock Braking System
Air Conditioner
Airbags
Bluetooth Compatibility

Why choose Cars24?

30-day easy returns
Lifetime Warranty Upgrade
Assured buyback
 Next

Exterior

Interior

Features

Highlights

Tyres

Great things about this car

Smart connectivity

with Apple CarPlay and Android Auto.

Fuel-efficient car

Drive more, spend less.

GPS connectivity

Precise navigation with in-built GPS.

Multitasking infotainment

8.0-inch screen for a rich experience.

Essential features

AC, power windows, music system.

184 mm ground clearance

High clearance for bumpy roads.

Car overview

Reg. year

Nov 2020

Fuel

Petrol

KM driven

33,425 km

Transmission

Manual

Engine capacity

999cc

Ownership

1st

Make year

Sep 2020

Spare key

No

Reg number

TS15**0127

Car inspection report

No accident history

No odometer tampering

No water damages

300-Quality checks

Cars24 inspected with 300-quality checks.

View inspection report
Features and specifications
Search for features & specifications

Features

Specifications

Bluetooth Compatibility
Airbags
DRL - Daytime Running Lights
ABS - Anti-lock Braking System
EBD - Electronic Brakeforce Distribution
Air Conditioner
Central Locking

Features and specifications bring superior driving experience and comfort.

View all

Why choose Cars24?

30-day easy returns

Buy it. Drive it, Return if it’s not right for you.

Guidelines →

Lifetime Warranty Upgrade

All cars come with a 13-month warranty — upgrade to get lifetime coverage.

Know more →

EMI calculator

EMI ESTIMATE

₹6,530 /month*

for 84 months @ 12%

Loan breakup

Car price

₹3,69,940

Down payment

- ₹0

Principal amount

₹3,69,940

Total interest payable

₹1,78,618

Monthly EMI @12%

₹6,530

EMI calculator

Down payment*
₹0
₹2,95,952
Tenure
12 months
84 months

*Final EMI gets calculated after income verification.

Check eligibility

This is just an example. Check eligibility for your final loan terms with zero down payment.

2020 Renault Kwid CLIMBER 1.0 (O)

33,425 km

1st owner

Manual

Petrol

TS-15

Bachupally, Hyderabad

Call us

Zero Worry Max
Lifetime warranty
30 days return
300+ quality checks
Best price
Core structure intact
No odometer tampering
No water damages
Inspection report available
RC transfer support

EMI starts at

₹6,530/mo

Check eligibility →

₹3.70 lakh

Includes RC transfer & more

Price breakup →

Book free test drive

Still can’t decide?

Explore cars similar to Renault Kwid

Previous
Cars24 Owned Stock
2021 Renault Kwid RXT 1.0 (O)

28,068 km

Petrol

Manual

TS-29

EMI ₹6,431/m*

₹4.05L

₹3.64 lakh

Includes RC transfer & more

Kompally, Hyderabad

Cars24 Owned Stock
2019 Renault Kwid RXT 1.0 (O)

35,758 km

Petrol

Manual

TS-09

EMI ₹6,027/m*

₹3.41 lakh

Includes RC transfer & more

Bachupally, Hyderabad

Cars24 Owned Stock
2017 Renault Kwid RXT 1.0

30,086 km

Petrol

Manual

TS-10

EMI ₹5,349/m*

₹3.10L

₹2.74 lakh

Includes RC transfer & more

Bachupally, Hyderabad

Cars24 Owned Stock
2019 Tata Tiago XZ PETROL

75,767 km

Petrol

Manual

TS-08

EMI ₹6,484/m*

₹4.06L

₹3.67 lakh

Includes RC transfer & more

Upperpally, Attapur, Hyderabad

Cars24 Owned Stock
2021 Tata Tiago XZ PLUS PETROL

1,06,107 km

Petrol

Manual

TS-36

EMI ₹9,561/m*

₹4.74L

₹4.30 lakh

Includes RC transfer & more

Bachupally, Hyderabad

Cars24 Owned Stock
2020 Hyundai NEW SANTRO SPORTZ MT

62,852 km

Petrol

Manual

TS-16

EMI ₹6,816/m*

₹4.18L

₹3.86 lakh

Includes RC transfer & more

Uppal, Hyderabad

Cars24 Owned Stock
2018 Maruti Celerio ZXI

70,380 km

Petrol

Manual

TS-07

EMI ₹6,590/m*

₹3.73 lakh

Includes RC transfer & more

Upperpally, Attapur, Hyderabad

Cars24 Owned Stock
2020 Maruti S PRESSO VXI PLUS AMT

25,046 km

Petrol

Auto

TS-09

EMI ₹6,852/m*

₹3.88 lakh

Includes RC transfer & more

Kompally, Hyderabad

Cars24 Owned Stock
2021 Maruti IGNIS SIGMA 1.2

24,060 km

Petrol

Manual

TS-11

EMI ₹7,617/m*

₹4.62L

₹4.31 lakh

Includes RC transfer & more

Uppal, Hyderabad

Cars24 Owned Stock
2020 Maruti IGNIS ALPHA 1.2

28,366 km

Petrol

Manual

TS-09

EMI ₹8,324/m*

₹5.54L

₹4.72 lakh

Includes RC transfer & more

GVK One Mall, Banjara Hills, Hyderabad, Telangana

Next
Explore more options
BY MODEL

Used Renault Kwid Cars in Hyderabad

BY BRAND

Used Renault Cars in Hyderabad

BY BUDGET

Used Cars under 4 Lakhs in Hyderabad

BY BODY TYPE

Used Hatchback Cars in Hyderabad

BY FUEL TYPE

Used Petrol Cars in Hyderabad

BY TRANSMISSION

Used Manual Cars in Hyderabad

Home
Used Cars
Used Cars In Hyderabad
Used Renault Cars In Hyderabad
Used Renault Kwid Cars In Hyderabad
Used 2020 Renault Kwid CLIMBER 1.0 (O) Manual

In [6]:
from playwright.async_api import async_playwright

url = "https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/"

async def inspect_structured_data():

    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page(
            viewport={"width": 1440, "height": 900}
        )

        await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        await page.wait_for_timeout(5000)

        # Check JSON-LD
        json_ld = await page.locator(
            'script[type="application/ld+json"]'
        ).all_text_contents()

        print("========== JSON-LD DATA ==========")
        print("Number of JSON-LD scripts:", len(json_ld))

        for i, data in enumerate(json_ld):
            print(f"\n--- JSON-LD {i+1} ---")
            print(data[:5000])

        # Check Next.js / page scripts containing vehicle information
        scripts = await page.locator("script").all_text_contents()

        print("\n========== VEHICLE DATA IN SCRIPTS ==========")

        found = 0

        for i, script in enumerate(scripts):

            if any(word.lower() in script.lower()
                   for word in [
                       "Renault",
                       "Kwid",
                       "CLIMBER",
                       "369940",
                       "370000",
                       "33425"
                   ]):

                print(f"\n--- Matching script {i} ---")
                print(script[:8000])

                found += 1

                if found >= 5:
                    break

        print("\nMatching scripts found:", found)

        await browser.close()


await inspect_structured_data()

========== JSON-LD DATA ==========
Number of JSON-LD scripts: 3

--- JSON-LD 1 ---
[{"@context":"https://schema.org/","@id":"https://www.cars24.com/","url":"https://www.cars24.com/","name":"Cars24","@type":"WebPage"},{"@context":"https://schema.org/","@id":"https://www.cars24.com/","url":"https://www.cars24.com/","name":"Cars24","@type":"Website"}]

--- JSON-LD 2 ---
{"@context":"http://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https://www.cars24.com/","name":"Home"}},{"@type":"ListItem","position":2,"item":{"@id":"https://www.cars24.com/buy-used-cars/","name":"Used Cars"}},{"@type":"ListItem","position":3,"item":{"@id":"https://www.cars24.com/buy-used-cars-hyderabad/","name":"Used Cars in Hyderabad"}},{"@type":"ListItem","position":4,"item":{"@id":"https://www.cars24.com/buy-used-renault-cars-hyderabad/","name":"Used Renault Cars in Hyderabad"}},{"@type":"ListItem","position":5,"item":{"@id":"https://www.cars24.com/buy-used-renault-kwid-cars-hyderabad/","name":"Used Renault Kwid Cars in Hyderabad"}},{"@type":"ListItem","position":6,"item":{"name":"Used 2020 Renault Kwid CLIMBER 1.0 (O) Manual"}}]}

--- JSON-LD 3 ---
{"@context":"https://schema.org","@type":"Car","name":"2020 Renault Kwid CLIMBER 1.0 (O)","brand":{"@type":"Brand","name":"Renault"},"model":"Kwid","vehicleModelDate":2020,"bodyType":"Hatchback","fuelType":"Petrol","vehicleTransmission":"Manual","offers":{"@type":"Offer","priceCurrency":"INR","price":369940,"itemCondition":"https://schema.org/UsedCondition","availability":"https://schema.org/InStock","url":"https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/"},"mileageFromOdometer":{"@type":"QuantitativeValue","value":33425,"unitCode":"KMT"},"image":["https://media.cars24.com/hello-ar/dev/transformed/uploads/58921deb-e476-447a-8062-bc30a90b97a6/39fb5b33-b464-4e02-ba9b-0a1faa2d0b2b/11fd99ff-e9fa-40fc-8037-bacee0524fc2/slot/2.jpg"]}

========== VEHICLE DATA IN SCRIPTS ==========

--- Matching script 38 ---
{"@context":"http://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"item":{"@id":"https://www.cars24.com/","name":"Home"}},{"@type":"ListItem","position":2,"item":{"@id":"https://www.cars24.com/buy-used-cars/","name":"Used Cars"}},{"@type":"ListItem","position":3,"item":{"@id":"https://www.cars24.com/buy-used-cars-hyderabad/","name":"Used Cars in Hyderabad"}},{"@type":"ListItem","position":4,"item":{"@id":"https://www.cars24.com/buy-used-renault-cars-hyderabad/","name":"Used Renault Cars in Hyderabad"}},{"@type":"ListItem","position":5,"item":{"@id":"https://www.cars24.com/buy-used-renault-kwid-cars-hyderabad/","name":"Used Renault Kwid Cars in Hyderabad"}},{"@type":"ListItem","position":6,"item":{"name":"Used 2020 Renault Kwid CLIMBER 1.0 (O) Manual"}}]}

--- Matching script 39 ---
{"@context":"https://schema.org","@type":"Car","name":"2020 Renault Kwid CLIMBER 1.0 (O)","brand":{"@type":"Brand","name":"Renault"},"model":"Kwid","vehicleModelDate":2020,"bodyType":"Hatchback","fuelType":"Petrol","vehicleTransmission":"Manual","offers":{"@type":"Offer","priceCurrency":"INR","price":369940,"itemCondition":"https://schema.org/UsedCondition","availability":"https://schema.org/InStock","url":"https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/"},"mileageFromOdometer":{"@type":"QuantitativeValue","value":33425,"unitCode":"KMT"},"image":["https://media.cars24.com/hello-ar/dev/transformed/uploads/58921deb-e476-447a-8062-bc30a90b97a6/39fb5b33-b464-4e02-ba9b-0a1faa2d0b2b/11fd99ff-e9fa-40fc-8037-bacee0524fc2/slot/2.jpg"]}

--- Matching script 44 ---
self.__next_f.push([1,"1f:I[11815,[],\"\"]\n22:I[55092,[],\"\"]\n24:I[82023,[],\"\"]\n26:I[87221,[\"68067\",\"static/chunks/app/desktop/layout-78a77a488464401c.js\"],\"default\"]\n2a:I[91584,[],\"\"]\n23:[\"params\",\"renault-kwid-2020/hyderabad/10457877130\",\"c\"]\n2b:[]\n"])

--- Matching script 45 ---
self.__next_f.push([1,"0:[\"$\",\"$L1f\",null,{\"buildId\":\"suIZ-uPAYH2krm-qMhE6Z\",\"assetPrefix\":\"https://assets.cars24.com/production/india-website/catalog/260918123035\",\"urlParts\":[\"\",\"buy-used-renault-kwid-2020-cars-hyderabad-10457877130\",\"\"],\"initialTree\":[\"\",{\"children\":[\"desktop\",{\"children\":[\"(non-dls)\",{\"children\":[\"buy-used-cars-detail\",{\"children\":[[\"params\",\"renault-kwid-2020/hyderabad/10457877130\",\"c\"],{\"children\":[\"__PAGE__\",{}]}]}]}]}]},\"$undefined\",\"$undefined\",true],\"initialSeedData\":[\"\",{\"children\":[\"desktop\",{\"children\":[\"(non-dls)\",{\"children\":[\"buy-used-cars-detail\",{\"children\":[[\"params\",\"renault-kwid-2020/hyderabad/10457877130\",\"c\"],{\"children\":[\"__PAGE__\",{},[[\"$L20\",\"$L21\",[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/b3a1dad41cdb7e91.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"1\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/738ef8d24ea977f6.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"2\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/c81db7aa73cdc889.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"3\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/211529ebd01533d0.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"4\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/767c1ed99a7d4abe.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"5\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/5c2648a4469ac161.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"6\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/dcb5417447251508.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"7\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/f7a4d98b0e3c6c71.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"8\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/17129326b6d5e6b3.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"9\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/94129f0101ee9679.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"10\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/a0cf61af3c0fccdb.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"11\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/f16dc81d8a19bcd2.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"12\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/6d244af9dccf57de.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"13\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/d2949aedbb1abd55.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}]]],null],null]},[null,[\"$\",\"$L22\",null,{\"parallelRouterKey\":\"children\",\"segmentPath\":[\"children\",\"desktop\",\"children\",\"(non-dls)\",\"children\",\"buy-used-cars-detail\",\"children\",\"$23\",\"children\"],\"error\":\"$undefined\",\"errorStyles\":\"$undefined\",\"errorScripts\":\"$undefined\",\"template\":[\"$\",\"$L24\",null,{}],\"templateStyles\":\"$undefined\",\"templateScripts\":\"$undefined\",\"notFound\":\"$undefined\",\"notFoundStyles\":\"$undefined\"}]],[[[\"$\",\"div\",null,{\"className\":\"container skeleton_header__Fndfe\",\"children\":[[\"$\",\"div\",null,{\"className\":\"skeleton_logoContainer__nEahD\",\"children\":[[\"$\",\"div\",null,{\"className\":\"shimmer skeleton_logo__1AGLL\"}],[\"$\",\"div\",null,{\"className\":\"shimmer skeleton_city__6SGwm\"}]]}],[\"$\",\"div\",null,{\"className\":\"skeleton_nav__DYMEr\",\"children\":[[\"$\",\"div\",\"0\",{\"className\":\"shimmer skeleton_menuItem__T_632\"}],[\"$\",\"div\",\"1\",{\"className\":\"shimmer skeleton_menuItem__T_632\"}],[\"$\",\"div\",\"2\",{\"className\":\"shimmer skeleton_menuItem__T_632\"}],[\"$\",\"div\",\"3\",{\"className\":\"shimmer skeleton_menuItem__T_632\"}],[\"$\",\"div\",\"4\",{\"className\":\"shimmer skeleton_menuItem__T_632\"}]]}],[\"$\",\"div\",null,{\"className\":\"skeleton_navRightWrapper__KrRsU\",\"children\":[[\"$\",\"div\",null,{\"className\":\"shimmer skeleton_menuIcon__qYjOq\"}],[\"$\",\"div\",null,{\"className\":\"shimmer skeleton_account__08s_5\"}]]}]]}],[\"$\",\"div\",null,{\"className\":\"container\",\"children\":[\"$\",\"div\",null,{\"className\":\"styles_skeletonContainer__efulL\",\"children\":[[\"$\",\"div\",null,{\"className\":\"styles_leftSection__wJcmj\",\"children\":[[\"$\",\"div\",null,{\"className\":\"shimmer styles_banner__jkYlB\"}],[\"$\",\"div\",null,{\"className\":\"styles_uspCard__Qdk5Y\",\"children\":[[\"$\",\"div\",null,{\"className\":\"shimmer styles_uspCardHeading__ug2uM\"}],[\"$\",\"div\",null,{\"className\":\"shimmer styles_uspIcon__wSN03\"}],[\"$\",\"div\",null,{\"className\":\"shimmer styles_uspContent__FfXUm\"}]]}],[\"$\",\"div\",null,{\"className\":\"shimmer styles_sectionCard__3oAwS\"}]]}],[\"$\",\"div\",null,{\"className\":\"styles_rightSection__tMKxc\",\"children\":[\"$\",\"div\",null,{\"className\":\"styles_carDetailSection__4y4Uz\",\"children\":[[\"$\",\"div\",null,{\"className\":\"styles_topFoldContainer__FxkLn\",\"children\":[[\"$\",\"div\",null,{\"className\":\"shimmer styles_carName___3BKv\"}],[\"$\",\"div\",null,{\"className\":\"shimmer styles_uspBadge__5srqr\"}],[\"$\",\"div\",null,{\"className\":\"shimmer styles_location___vfwC\"}],[\"$\",\"div\",null,{\"className\":\"shimmer styles_assured__RbkQs\"}]]}],[\"$\",\"div\",null,{\"className\":\"shimmer styles_priceBox__ogZ0e\"}],[\"$\",\"div\",null,{\"className\":\"shimmer styles_button__KW77P\"}]]}]}]]}]}]],[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/d1cad41d8eff2618.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"1\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/5c2648a4469ac161.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}]],[]]]},[null,[\"$\",\"$L22\",null,{\"parallelRouterKey\":\"children\",\"segmentPath\":[\"children\",\"desktop\",\"children\",\"(non-dls)\",\"children\",\"buy-used-cars-detail\",\"children\"],\"error\":\"$undefined\",\"errorStyles\":\"$undefined\",\"errorScripts\":\"$undefined\",\"template\":[\"$\",\"$L24\",null,{}],\"templateStyles\":\"$undefined\",\"templateScripts\":\"$undefined\",\"notFound\":\"$undefined\",\"notFoundStyles\":\"$undefined\"}]],null]},[[[[\"$\",\"link\",\"0\",{\"rel\":\"stylesheet\",\"href\":\"https://assets.cars24.com/production/india-website/catalog/260918123035/_next/static/css/12fb2be01d7aabef.css\",\"precedence\":\"next\",\"crossOrigin\":\"$undefined\"}],[\"$\",\"link\",\"1\",{\"rel\":\"stylesheet\",\"href\":\"htt

--- Matching script 81 ---

In [7]:
    import json
import pandas as pd
from playwright.async_api import async_playwright

url = "https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/"

async def extract_car(url):

    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page(
            viewport={"width": 1440, "height": 900}
        )

        await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        await page.wait_for_timeout(3000)

        json_ld_scripts = await page.locator(
            'script[type="application/ld+json"]'
        ).all_text_contents()

        car_data = None

        for script in json_ld_scripts:

            try:
                data = json.loads(script)

                # JSON-LD can be a list or dictionary
                items = data if isinstance(data, list) else [data]

                for item in items:

                    if (
                        isinstance(item, dict)
                        and item.get("@type") == "Car"
                    ):
                        car_data = item
                        break

            except Exception:
                continue

            if car_data:
                break

        await browser.close()

        if not car_data:
            return None

        # Extract values
        brand = car_data.get("brand", {})
        brand = (
            brand.get("name")
            if isinstance(brand, dict)
            else brand
        )

        offer = car_data.get("offers", {})

        mileage = car_data.get("mileageFromOdometer", {})

        record = {
            "listing_url": url,
            "car_name": car_data.get("name"),
            "brand": brand,
            "model": car_data.get("model"),
            "manufacturing_year": car_data.get("vehicleModelDate"),
            "body_type": car_data.get("bodyType"),
            "fuel_type": car_data.get("fuelType"),
            "transmission": car_data.get("vehicleTransmission"),
            "price": offer.get("price"),
            "price_currency": offer.get("priceCurrency"),
            "km_driven": mileage.get("value"),
        }

        return record


record = await extract_car(url)

df_test = pd.DataFrame([record])

display(df_test)

IndentationError: unexpected indent (3808823141.py, line 1)

In [8]:
import json
import pandas as pd
from playwright.async_api import async_playwright

url = "https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/"

async def extract_car(url):

    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page(
            viewport={"width": 1440, "height": 900}
        )

        await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        await page.wait_for_timeout(3000)

        json_ld_scripts = await page.locator(
            'script[type="application/ld+json"]'
        ).all_text_contents()

        car_data = None

        for script in json_ld_scripts:

            try:
                data = json.loads(script)

                # JSON-LD can be a list or dictionary
                items = data if isinstance(data, list) else [data]

                for item in items:

                    if (
                        isinstance(item, dict)
                        and item.get("@type") == "Car"
                    ):
                        car_data = item
                        break

            except Exception:
                continue

            if car_data:
                break

        await browser.close()

        if not car_data:
            return None

        # Extract values
        brand = car_data.get("brand", {})
        brand = (
            brand.get("name")
            if isinstance(brand, dict)
            else brand
        )

        offer = car_data.get("offers", {})

        mileage = car_data.get("mileageFromOdometer", {})

        record = {
            "listing_url": url,
            "car_name": car_data.get("name"),
            "brand": brand,
            "model": car_data.get("model"),
            "manufacturing_year": car_data.get("vehicleModelDate"),
            "body_type": car_data.get("bodyType"),
            "fuel_type": car_data.get("fuelType"),
            "transmission": car_data.get("vehicleTransmission"),
            "price": offer.get("price"),
            "price_currency": offer.get("priceCurrency"),
            "km_driven": mileage.get("value"),
        }

        return record


record = await extract_car(url)

df_test = pd.DataFrame([record])

display(df_test)

,listing_url,car_name,brand,model,manufacturing_year,body_type,fuel_type,transmission,price,price_currency,km_driven
0,https://www.cars24.com/buy-used-renault-kwid-2...,2020 Renault Kwid CLIMBER 1.0 (O),Renault,Kwid,2020,Hatchback,Petrol,Manual,369940,INR,33425

In [9]:
import re
from playwright.async_api import async_playwright

CITY_URL = "https://www.cars24.com/buy-used-cars-hyderabad/"

async def collect_listing_urls():

    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page(
            viewport={"width": 1440, "height": 900}
        )

        print("Opening Cars24 Hyderabad...")

        await page.goto(
            CITY_URL,
            wait_until="domcontentloaded",
            timeout=60000
        )

        await page.wait_for_timeout(5000)

        # Scroll to load more cars
        for i in range(8):

            await page.mouse.wheel(0, 4000)

            await page.wait_for_timeout(2000)

            print(f"Scroll {i + 1}/8 completed")

        # Get all links
        links = await page.locator("a[href]").evaluate_all(
            """els => els.map(a => ({
                href: a.href,
                text: (a.innerText || '').trim()
            }))"""
        )

        listing_urls = []

        for item in links:

            href = item["href"]

            # Remove query parameters
            href = href.split("?")[0].rstrip("/")

            # Actual listing pages contain numeric listing ID
            if re.search(r"-\d{8,}$", href):

                listing_urls.append(href + "/")

        # Remove duplicates
        listing_urls = list(dict.fromkeys(listing_urls))

        print("\n====================================")
        print("TOTAL LINKS FOUND:", len(links))
        print("INDIVIDUAL LISTINGS:", len(listing_urls))
        print("====================================")

        print("\nFirst 20 listing URLs:\n")

        for i, url in enumerate(listing_urls[:20], 1):

            print(i, url)

        await browser.close()

        return listing_urls


listing_urls = await collect_listing_urls()

Opening Cars24 Hyderabad...
Scroll 1/8 completed
Scroll 2/8 completed
Scroll 3/8 completed
Scroll 4/8 completed
Scroll 5/8 completed
Scroll 6/8 completed
Scroll 7/8 completed
Scroll 8/8 completed

====================================
TOTAL LINKS FOUND: 499
INDIVIDUAL LISTINGS: 20
====================================

First 20 listing URLs:

1 https://www.cars24.com/buy-used-maruti-swift-2024-cars-hyderabad-10440373131/
2 https://www.cars24.com/buy-used-renault-kwid-2017-cars-hyderabad-10473477137/
3 https://www.cars24.com/buy-used-maruti-swift-2018-cars-hyderabad-10432970186/
4 https://www.cars24.com/buy-used-tata-nexon-2022-cars-hyderabad-10425496120/
5 https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/
6 https://www.cars24.com/buy-used-tata-nexon-2020-cars-hyderabad-10420372181/
7 https://www.cars24.com/buy-used-volkswagen-polo-2017-cars-hyderabad-10420673116/
8 https://www.cars24.com/buy-used-hyundai-elite-i20-2017-cars-hyderabad-10488773188/
9 https://www.cars24.com/buy-used-ford-ecosport-2019-cars-hyderabad-10481879115/
10 https://www.cars24.com/buy-used-tata-altroz-2021-cars-hyderabad-12218574193/
11 https://www.cars24.com/buy-used-maruti-baleno-2018-cars-hyderabad-10453071185/
12 https://www.cars24.com/buy-used-mg-hector-plus-2022-cars-hyderabad-12259695148/
13 https://www.cars24.com/buy-used-kia-sonet-2020-cars-hyderabad-12217979194/
14 https://www.cars24.com/buy-used-mahindra-xuv700-2022-cars-hyderabad-10486470157/
15 https://www.cars24.com/buy-used-tata-indica-vista-2014-cars-hyderabad-12171393104/
16 https://www.cars24.com/buy-used-mahindra-xuv700-2022-cars-hyderabad-10430072195/
17 https://www.cars24.com/buy-used-maruti-wagon-r-1.0-2017-cars-hyderabad-10409075118/
18 https://www.cars24.com/buy-used-hyundai-verna-2019-cars-hyderabad-10489571111/
19 https://www.cars24.com/buy-used-datsun-redi-go-2019-cars-hyderabad-10441774184/
20 https://www.cars24.com/buy-used-toyota-yaris-2018-cars-hyderabad-10427399135/

In [10]:
import asyncio
import json
import pandas as pd
from playwright.async_api import async_playwright


async def extract_car_data(page, url):

    try:

        await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        await page.wait_for_timeout(1500)

        json_ld_scripts = await page.locator(
            'script[type="application/ld+json"]'
        ).all_text_contents()

        car = None

        for script in json_ld_scripts:

            try:

                data = json.loads(script)

                items = data if isinstance(data, list) else [data]

                for item in items:

                    if (
                        isinstance(item, dict)
                        and item.get("@type") == "Car"
                    ):
                        car = item
                        break

            except Exception:
                continue

            if car:
                break

        if not car:
            print("❌ No Car JSON-LD:", url)
            return None

        brand = car.get("brand", {})

        if isinstance(brand, dict):
            brand = brand.get("name")

        offer = car.get("offers", {})

        mileage = car.get(
            "mileageFromOdometer",
            {}
        )

        return {
            "listing_url": url,
            "car_name": car.get("name"),
            "brand": brand,
            "model": car.get("model"),
            "manufacturing_year": car.get(
                "vehicleModelDate"
            ),
            "body_type": car.get("bodyType"),
            "fuel_type": car.get("fuelType"),
            "transmission": car.get(
                "vehicleTransmission"
            ),
            "price_numeric": offer.get("price"),
            "price_currency": offer.get(
                "priceCurrency"
            ),
            "km_driven": mileage.get("value"),
        }

    except Exception as e:

        print("❌ Error:", url)
        print(str(e))

        return None


async def scrape_test_listings(urls):

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=True
        )

        page = await browser.new_page(
            viewport={
                "width": 1440,
                "height": 900
            }
        )

        results = []

        for i, url in enumerate(urls, 1):

            print(
                f"Scraping {i}/{len(urls)}"
            )

            data = await extract_car_data(
                page,
                url
            )

            if data:
                results.append(data)

            # Small delay between pages
            await asyncio.sleep(1)

        await browser.close()

        return results


test_data = await scrape_test_listings(
    listing_urls
)

df_test_20 = pd.DataFrame(test_data)

print("\n==============================")
print("RESULT")
print("==============================")
print("URLs:", len(listing_urls))
print("Successfully extracted:", len(df_test_20))

display(df_test_20)

Scraping 1/20
Scraping 2/20
Scraping 3/20
Scraping 4/20
Scraping 5/20
Scraping 6/20
Scraping 7/20
Scraping 8/20
Scraping 9/20
Scraping 10/20
Scraping 11/20
Scraping 12/20
Scraping 13/20
Scraping 14/20
Scraping 15/20
Scraping 16/20
Scraping 17/20
Scraping 18/20
Scraping 19/20
Scraping 20/20

==============================
RESULT
==============================
URLs: 20
Successfully extracted: 20

,listing_url,car_name,brand,model,manufacturing_year,body_type,fuel_type,transmission,price_numeric,price_currency,km_driven
0,https://www.cars24.com/buy-used-maruti-swift-2...,2024 Maruti Swift VXi (O),Maruti,Swift,2024,Hatchback,Petrol,Manual,695840,INR,15400
1,https://www.cars24.com/buy-used-renault-kwid-2...,2017 Renault Kwid CLIMBER 1.0,Renault,Kwid,2017,Hatchback,Petrol,Manual,270614,INR,71447
2,https://www.cars24.com/buy-used-maruti-swift-2...,2018 Maruti Swift VDI,Maruti,Swift,2018,Hatchback,Diesel,Manual,562075,INR,83771
3,https://www.cars24.com/buy-used-tata-nexon-202...,2022 Tata NEXON XM SUNROOF PETROL,Tata,NEXON,2022,SUV,Petrol,Manual,654840,INR,54649
4,https://www.cars24.com/buy-used-renault-kwid-2...,2020 Renault Kwid CLIMBER 1.0 (O),Renault,Kwid,2020,Hatchback,Petrol,Manual,369940,INR,33425
5,https://www.cars24.com/buy-used-tata-nexon-202...,2020 Tata NEXON XZ PLUS (O) PETROL,Tata,NEXON,2020,SUV,Petrol,Manual,716403,INR,89034
6,https://www.cars24.com/buy-used-volkswagen-pol...,2017 Volkswagen Polo HIGHLINE PLUS 1.2(16 ALLOY,Volkswagen,Polo,2017,Hatchback,Petrol,Manual,515246,INR,41547
7,https://www.cars24.com/buy-used-hyundai-elite-...,2017 Hyundai Elite i20 SPORTZ 1.2,Hyundai,Elite i20,2017,Hatchback,Petrol,Manual,467376,INR,57809
8,https://www.cars24.com/buy-used-ford-ecosport-...,2019 Ford Ecosport TITANIUM 1.5L PETROL,Ford,Ecosport,2019,SUV,Petrol,Manual,515576,INR,78135
9,https://www.cars24.com/buy-used-tata-altroz-20...,2021 Tata ALTROZ XT I-TURBO PETROL,Tata,ALTROZ,2021,Hatchback,Petrol,Manual,613840,INR,104414
10,https://www.cars24.com/buy-used-maruti-baleno-...,2018 Maruti Baleno ALPHA PETROL 1.2,Maruti,Baleno,2018,Hatchback,Petrol,Manual,563276,INR,44011
11,https://www.cars24.com/buy-used-mg-hector-plus...,2022 MG HECTOR PLUS SELECT 2.0 DIESEL TURBO MT...,MG,HECTOR PLUS,2022,SUV,Diesel,Manual,1174000,INR,61224
12,https://www.cars24.com/buy-used-kia-sonet-2020...,2020 KIA SONET GTX PLUS 1.0 DCT DUAL TONE,KIA,SONET,2020,SUV,Petrol,Automatic,787840,INR,65337
13,https://www.cars24.com/buy-used-mahindra-xuv70...,2022 Mahindra XUV700 AX 5 P MT 5 STR,Mahindra,XUV700,2022,SUV,Petrol,Manual,1108100,INR,45924
14,https://www.cars24.com/buy-used-tata-indica-vi...,2014 Tata Indica Vista VX TECH QUADRAJET,Tata,Indica Vista,2014,Hatchback,Diesel,Manual,212936,INR,38245
15,https://www.cars24.com/buy-used-mahindra-xuv70...,2022 Mahindra XUV700 AX 3 P MT 5 STR,Mahindra,XUV700,2022,SUV,Petrol,Manual,1019197,INR,82103
16,https://www.cars24.com/buy-used-maruti-wagon-r...,2017 Maruti Wagon R 1.0 VXI AMT,Maruti,Wagon R 1.0,2017,Hatchback,Petrol,Automatic,388337,INR,14587
17,https://www.cars24.com/buy-used-hyundai-verna-...,2019 Hyundai Verna 1.6 VTVT SX,Hyundai,Verna,2019,Sedan,Petrol,Manual,646117,INR,70175
18,https://www.cars24.com/buy-used-datsun-redi-go...,2019 Datsun Redi Go S 1.0,Datsun,Redi Go,2019,Hatchback,Petrol,Manual,243614,INR,45340
19,https://www.cars24.com/buy-used-toyota-yaris-2...,2018 Toyota YARIS G CVT,Toyota,YARIS,2018,Sedan,Petrol,Automatic,523916,INR,74307

In [11]:
import re
from playwright.async_api import async_playwright

url = "https://www.cars24.com/buy-used-cars-bangalore/"

async with async_playwright() as p:

    browser = await p.chromium.launch(headless=True)

    page = await browser.new_page(
        viewport={"width": 1440, "height": 900}
    )

    print("Opening Bangalore...")

    await page.goto(
        url,
        wait_until="domcontentloaded",
        timeout=60000
    )

    await page.wait_for_timeout(5000)

    for i in range(10):
        await page.mouse.wheel(0, 4000)
        await page.wait_for_timeout(2000)
        print(f"Scroll {i+1}/10")

    links = await page.locator(
        "a[href]"
    ).evaluate_all(
        """els => els.map(a => a.href)"""
    )

    listing_urls = []

    for href in links:

        href = href.split("?")[0].rstrip("/")

        if re.search(r"-\d{8,}$", href):
            listing_urls.append(href + "/")

    listing_urls = list(dict.fromkeys(listing_urls))

    print("\n==============================")
    print("TOTAL LINKS:", len(links))
    print("INDIVIDUAL LISTINGS:", len(listing_urls))
    print("==============================")

    for i, listing in enumerate(listing_urls[:20], 1):
        print(i, listing)

    await browser.close()

Opening Bangalore...
Scroll 1/10
Scroll 2/10
Scroll 3/10
Scroll 4/10
Scroll 5/10
Scroll 6/10
Scroll 7/10
Scroll 8/10
Scroll 9/10
Scroll 10/10

==============================
TOTAL LINKS: 502
INDIVIDUAL LISTINGS: 20
==============================
1 https://www.cars24.com/buy-used-renault-kwid-2025-cars-bangalore-13189872131/
2 https://www.cars24.com/buy-used-maruti-swift-2026-cars-bangalore-10285571135/
3 https://www.cars24.com/buy-used-maruti-vitara-brezza-2022-cars-bangalore-10036890169/
4 https://www.cars24.com/buy-used-hyundai-creta-2017-cars-bangalore-10212775137/
5 https://www.cars24.com/buy-used-renault-kwid-2019-cars-bangalore-11124674158/
6 https://www.cars24.com/buy-used-maruti-swift-2021-cars-bangalore-10213479135/
7 https://www.cars24.com/buy-used-maruti-vitara-brezza-2022-cars-bangalore-10079972150/
8 https://www.cars24.com/buy-used-maruti-ignis-2021-cars-bangalore-11128274157/
9 https://www.cars24.com/buy-used-tata-nexon-2021-cars-bangalore-10202069755/
10 https://www.cars24.com/buy-used-tata-nexon-2018-cars-bangalore-23584671192/
11 https://www.cars24.com/buy-used-ford-ecosport-2019-cars-bangalore-10256378133/
12 https://www.cars24.com/buy-used-renault-kwid-2020-cars-bangalore-10042777191/
13 https://www.cars24.com/buy-used-kia-sonet-2022-cars-bangalore-10200173177/
14 https://www.cars24.com/buy-used-maruti-alto-k10-2014-cars-bangalore-16596994193/
15 https://www.cars24.com/buy-used-renault-kwid-2024-cars-bangalore-10236273131/
16 https://www.cars24.com/buy-used-renault-duster-2020-cars-bangalore-10817696177/
17 https://www.cars24.com/buy-used-volkswagen-polo-2019-cars-bangalore-10220979187/
18 https://www.cars24.com/buy-used-maruti-eeco-2023-cars-bangalore-10083867767/
19 https://www.cars24.com/buy-used-tata-nexon-2023-cars-bangalore-10859770115/
20 https://www.cars24.com/buy-used-toyota-glanza-2022-cars-bangalore-10256770114/

In [12]:
# Save Bangalore URLs
bangalore_urls = listing_urls if "listing_urls" in globals() else []

print("Bangalore URLs saved:", len(bangalore_urls))

for i, url in enumerate(bangalore_urls, 1):
    print(i, url)

Bangalore URLs saved: 20
1 https://www.cars24.com/buy-used-renault-kwid-2025-cars-bangalore-13189872131/
2 https://www.cars24.com/buy-used-maruti-swift-2026-cars-bangalore-10285571135/
3 https://www.cars24.com/buy-used-maruti-vitara-brezza-2022-cars-bangalore-10036890169/
4 https://www.cars24.com/buy-used-hyundai-creta-2017-cars-bangalore-10212775137/
5 https://www.cars24.com/buy-used-renault-kwid-2019-cars-bangalore-11124674158/
6 https://www.cars24.com/buy-used-maruti-swift-2021-cars-bangalore-10213479135/
7 https://www.cars24.com/buy-used-maruti-vitara-brezza-2022-cars-bangalore-10079972150/
8 https://www.cars24.com/buy-used-maruti-ignis-2021-cars-bangalore-11128274157/
9 https://www.cars24.com/buy-used-tata-nexon-2021-cars-bangalore-10202069755/
10 https://www.cars24.com/buy-used-tata-nexon-2018-cars-bangalore-23584671192/
11 https://www.cars24.com/buy-used-ford-ecosport-2019-cars-bangalore-10256378133/
12 https://www.cars24.com/buy-used-renault-kwid-2020-cars-bangalore-10042777191/
13 https://www.cars24.com/buy-used-kia-sonet-2022-cars-bangalore-10200173177/
14 https://www.cars24.com/buy-used-maruti-alto-k10-2014-cars-bangalore-16596994193/
15 https://www.cars24.com/buy-used-renault-kwid-2024-cars-bangalore-10236273131/
16 https://www.cars24.com/buy-used-renault-duster-2020-cars-bangalore-10817696177/
17 https://www.cars24.com/buy-used-volkswagen-polo-2019-cars-bangalore-10220979187/
18 https://www.cars24.com/buy-used-maruti-eeco-2023-cars-bangalore-10083867767/
19 https://www.cars24.com/buy-used-tata-nexon-2023-cars-bangalore-10859770115/
20 https://www.cars24.com/buy-used-toyota-glanza-2022-cars-bangalore-10256770114/

In [13]:
# Check Bangalore URLs

print("Total Bangalore URLs:", len(bangalore_urls))

# Remove duplicates
bangalore_urls = list(dict.fromkeys(bangalore_urls))

print("Unique Bangalore URLs:", len(bangalore_urls))

# Show all URLs
for i, url in enumerate(bangalore_urls, 1):
    print(i, url)

Total Bangalore URLs: 20
Unique Bangalore URLs: 20
1 https://www.cars24.com/buy-used-renault-kwid-2025-cars-bangalore-13189872131/
2 https://www.cars24.com/buy-used-maruti-swift-2026-cars-bangalore-10285571135/
3 https://www.cars24.com/buy-used-maruti-vitara-brezza-2022-cars-bangalore-10036890169/
4 https://www.cars24.com/buy-used-hyundai-creta-2017-cars-bangalore-10212775137/
5 https://www.cars24.com/buy-used-renault-kwid-2019-cars-bangalore-11124674158/
6 https://www.cars24.com/buy-used-maruti-swift-2021-cars-bangalore-10213479135/
7 https://www.cars24.com/buy-used-maruti-vitara-brezza-2022-cars-bangalore-10079972150/
8 https://www.cars24.com/buy-used-maruti-ignis-2021-cars-bangalore-11128274157/
9 https://www.cars24.com/buy-used-tata-nexon-2021-cars-bangalore-10202069755/
10 https://www.cars24.com/buy-used-tata-nexon-2018-cars-bangalore-23584671192/
11 https://www.cars24.com/buy-used-ford-ecosport-2019-cars-bangalore-10256378133/
12 https://www.cars24.com/buy-used-renault-kwid-2020-cars-bangalore-10042777191/
13 https://www.cars24.com/buy-used-kia-sonet-2022-cars-bangalore-10200173177/
14 https://www.cars24.com/buy-used-maruti-alto-k10-2014-cars-bangalore-16596994193/
15 https://www.cars24.com/buy-used-renault-kwid-2024-cars-bangalore-10236273131/
16 https://www.cars24.com/buy-used-renault-duster-2020-cars-bangalore-10817696177/
17 https://www.cars24.com/buy-used-volkswagen-polo-2019-cars-bangalore-10220979187/
18 https://www.cars24.com/buy-used-maruti-eeco-2023-cars-bangalore-10083867767/
19 https://www.cars24.com/buy-used-tata-nexon-2023-cars-bangalore-10859770115/
20 https://www.cars24.com/buy-used-toyota-glanza-2022-cars-bangalore-10256770114/

In [14]:
# Save the current Bangalore URLs separately
bangalore_listing_urls = bangalore_urls.copy()

print("Bangalore listings saved:", len(bangalore_listing_urls))

Bangalore listings saved: 20

In [15]:
import re
from playwright.async_api import async_playwright

hyderabad_url = "https://www.cars24.com/buy-used-cars-hyderabad/"

async with async_playwright() as p:

    browser = await p.chromium.launch(headless=True)

    page = await browser.new_page(
        viewport={"width": 1440, "height": 900}
    )

    print("Opening Hyderabad...")

    await page.goto(
        hyderabad_url,
        wait_until="domcontentloaded",
        timeout=60000
    )

    await page.wait_for_timeout(5000)

    for i in range(10):
        await page.mouse.wheel(0, 4000)
        await page.wait_for_timeout(2000)
        print(f"Scroll {i + 1}/10")

    links = await page.locator(
        "a[href]"
    ).evaluate_all(
        """els => els.map(a => a.href)"""
    )

    hyderabad_listing_urls = []

    for href in links:

        href = href.split("?")[0].rstrip("/")

        if re.search(r"-\d{8,}$", href):
            hyderabad_listing_urls.append(
                href + "/"
            )

    hyderabad_listing_urls = list(
        dict.fromkeys(hyderabad_listing_urls)
    )

    print("\n==============================")
    print(
        "Valid Hyderabad listings:",
        len(hyderabad_listing_urls)
    )
    print("==============================")

    for i, url in enumerate(
        hyderabad_listing_urls, 1
    ):
        print(i, url)

    await browser.close()

Opening Hyderabad...
Scroll 1/10
Scroll 2/10
Scroll 3/10
Scroll 4/10
Scroll 5/10
Scroll 6/10
Scroll 7/10
Scroll 8/10
Scroll 9/10
Scroll 10/10

==============================
Valid Hyderabad listings: 20
==============================
1 https://www.cars24.com/buy-used-maruti-swift-2024-cars-hyderabad-10440373131/
2 https://www.cars24.com/buy-used-renault-kwid-2017-cars-hyderabad-10473477137/
3 https://www.cars24.com/buy-used-maruti-swift-2018-cars-hyderabad-10432970186/
4 https://www.cars24.com/buy-used-tata-nexon-2022-cars-hyderabad-10425496120/
5 https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/
6 https://www.cars24.com/buy-used-tata-nexon-2020-cars-hyderabad-10420372181/
7 https://www.cars24.com/buy-used-volkswagen-polo-2017-cars-hyderabad-10420673116/
8 https://www.cars24.com/buy-used-hyundai-elite-i20-2017-cars-hyderabad-10488773188/
9 https://www.cars24.com/buy-used-ford-ecosport-2019-cars-hyderabad-10481879115/
10 https://www.cars24.com/buy-used-tata-altroz-2021-cars-hyderabad-12218574193/
11 https://www.cars24.com/buy-used-maruti-baleno-2018-cars-hyderabad-10453071185/
12 https://www.cars24.com/buy-used-mg-hector-plus-2022-cars-hyderabad-12259695148/
13 https://www.cars24.com/buy-used-kia-sonet-2020-cars-hyderabad-12217979194/
14 https://www.cars24.com/buy-used-mahindra-xuv700-2022-cars-hyderabad-10486470157/
15 https://www.cars24.com/buy-used-tata-indica-vista-2014-cars-hyderabad-12171393104/
16 https://www.cars24.com/buy-used-mahindra-xuv700-2022-cars-hyderabad-10430072195/
17 https://www.cars24.com/buy-used-maruti-wagon-r-1.0-2017-cars-hyderabad-10409075118/
18 https://www.cars24.com/buy-used-hyundai-verna-2019-cars-hyderabad-10489571111/
19 https://www.cars24.com/buy-used-datsun-redi-go-2019-cars-hyderabad-10441774184/
20 https://www.cars24.com/buy-used-toyota-yaris-2018-cars-hyderabad-10427399135/

In [16]:
# Combine Hyderabad + Bangalore URLs

all_listing_urls = (
    hyderabad_listing_urls
    + bangalore_listing_urls
)

# Remove duplicate URLs
all_listing_urls = list(
    dict.fromkeys(all_listing_urls)
)

print("Hyderabad listings:", len(hyderabad_listing_urls))
print("Bangalore listings:", len(bangalore_listing_urls))
print("Total unique listings:", len(all_listing_urls))

print("\nFirst 10 URLs:")
for i, url in enumerate(all_listing_urls[:10], 1):
    print(i, url)

Hyderabad listings: 20
Bangalore listings: 20
Total unique listings: 40

First 10 URLs:
1 https://www.cars24.com/buy-used-maruti-swift-2024-cars-hyderabad-10440373131/
2 https://www.cars24.com/buy-used-renault-kwid-2017-cars-hyderabad-10473477137/
3 https://www.cars24.com/buy-used-maruti-swift-2018-cars-hyderabad-10432970186/
4 https://www.cars24.com/buy-used-tata-nexon-2022-cars-hyderabad-10425496120/
5 https://www.cars24.com/buy-used-renault-kwid-2020-cars-hyderabad-10457877130/
6 https://www.cars24.com/buy-used-tata-nexon-2020-cars-hyderabad-10420372181/
7 https://www.cars24.com/buy-used-volkswagen-polo-2017-cars-hyderabad-10420673116/
8 https://www.cars24.com/buy-used-hyundai-elite-i20-2017-cars-hyderabad-10488773188/
9 https://www.cars24.com/buy-used-ford-ecosport-2019-cars-hyderabad-10481879115/
10 https://www.cars24.com/buy-used-tata-altroz-2021-cars-hyderabad-12218574193/

In [17]:
import asyncio
import json
import pandas as pd
from playwright.async_api import async_playwright


async def scrape_car(url, page):

    try:
        await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        await page.wait_for_timeout(1500)

        scripts = await page.locator(
            'script[type="application/ld+json"]'
        ).all_text_contents()

        car = None

        for script in scripts:

            try:
                data = json.loads(script)

                items = data if isinstance(data, list) else [data]

                for item in items:

                    if (
                        isinstance(item, dict)
                        and item.get("@type") == "Car"
                    ):
                        car = item
                        break

            except Exception:
                continue

            if car:
                break

        if not car:
            print("❌ No car data:", url)
            return None

        brand = car.get("brand", {})

        if isinstance(brand, dict):
            brand = brand.get("name")

        offer = car.get("offers", {})
        mileage = car.get("mileageFromOdometer", {})

        return {
            "listing_url": url,
            "car_name": car.get("name"),
            "brand": brand,
            "model": car.get("model"),
            "manufacturing_year": car.get("vehicleModelDate"),
            "body_type": car.get("bodyType"),
            "fuel_type": car.get("fuelType"),
            "transmission": car.get("vehicleTransmission"),
            "price_numeric": offer.get("price"),
            "price_currency": offer.get("priceCurrency"),
            "km_driven": mileage.get("value")
        }

    except Exception as e:
        print("❌ Error:", url)
        print(e)
        return None


async def scrape_all_40(urls):

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=True
        )

        page = await browser.new_page(
            viewport={
                "width": 1440,
                "height": 900
            }
        )

        results = []

        for i, url in enumerate(urls, 1):

            print(
                f"Scraping {i}/{len(urls)}"
            )

            data = await scrape_car(
                url,
                page
            )

            if data:
                results.append(data)

            await asyncio.sleep(1)

        await browser.close()

        return results


cars_40 = await scrape_all_40(
    all_listing_urls
)

df_40 = pd.DataFrame(cars_40)

print("\n==============================")
print("SCRAPING COMPLETE")
print("==============================")
print("URLs:", len(all_listing_urls))
print("Records:", len(df_40))
print("Duplicate URLs:", df_40["listing_url"].duplicated().sum())

display(df_40)

Scraping 1/40
Scraping 2/40
Scraping 3/40
Scraping 4/40
Scraping 5/40
Scraping 6/40
Scraping 7/40
Scraping 8/40
Scraping 9/40
Scraping 10/40
Scraping 11/40
Scraping 12/40
Scraping 13/40
Scraping 14/40
Scraping 15/40
Scraping 16/40
Scraping 17/40
Scraping 18/40
Scraping 19/40
Scraping 20/40
Scraping 21/40
Scraping 22/40
Scraping 23/40
Scraping 24/40
Scraping 25/40
Scraping 26/40
Scraping 27/40
Scraping 28/40
Scraping 29/40
Scraping 30/40
Scraping 31/40
Scraping 32/40
Scraping 33/40
Scraping 34/40
Scraping 35/40
Scraping 36/40
Scraping 37/40
Scraping 38/40
Scraping 39/40
Scraping 40/40

==============================
SCRAPING COMPLETE
==============================
URLs: 40
Records: 40
Duplicate URLs: 0

,listing_url,car_name,brand,model,manufacturing_year,body_type,fuel_type,transmission,price_numeric,price_currency,km_driven
0,https://www.cars24.com/buy-used-maruti-swift-2...,2024 Maruti Swift VXi (O),Maruti,Swift,2024,Hatchback,Petrol,Manual,695840,INR,15400
1,https://www.cars24.com/buy-used-renault-kwid-2...,2017 Renault Kwid CLIMBER 1.0,Renault,Kwid,2017,Hatchback,Petrol,Manual,270614,INR,71447
2,https://www.cars24.com/buy-used-maruti-swift-2...,2018 Maruti Swift VDI,Maruti,Swift,2018,Hatchback,Diesel,Manual,562075,INR,83771
3,https://www.cars24.com/buy-used-tata-nexon-202...,2022 Tata NEXON XM SUNROOF PETROL,Tata,NEXON,2022,SUV,Petrol,Manual,654840,INR,54649
4,https://www.cars24.com/buy-used-renault-kwid-2...,2020 Renault Kwid CLIMBER 1.0 (O),Renault,Kwid,2020,Hatchback,Petrol,Manual,369940,INR,33425
5,https://www.cars24.com/buy-used-tata-nexon-202...,2020 Tata NEXON XZ PLUS (O) PETROL,Tata,NEXON,2020,SUV,Petrol,Manual,716403,INR,89034
6,https://www.cars24.com/buy-used-volkswagen-pol...,2017 Volkswagen Polo HIGHLINE PLUS 1.2(16 ALLOY,Volkswagen,Polo,2017,Hatchback,Petrol,Manual,515246,INR,41547
7,https://www.cars24.com/buy-used-hyundai-elite-...,2017 Hyundai Elite i20 SPORTZ 1.2,Hyundai,Elite i20,2017,Hatchback,Petrol,Manual,467376,INR,57809
8,https://www.cars24.com/buy-used-ford-ecosport-...,2019 Ford Ecosport TITANIUM 1.5L PETROL,Ford,Ecosport,2019,SUV,Petrol,Manual,515576,INR,78135
9,https://www.cars24.com/buy-used-tata-altroz-20...,2021 Tata ALTROZ XT I-TURBO PETROL,Tata,ALTROZ,2021,Hatchback,Petrol,Manual,613840,INR,104414
10,https://www.cars24.com/buy-used-maruti-baleno-...,2018 Maruti Baleno ALPHA PETROL 1.2,Maruti,Baleno,2018,Hatchback,Petrol,Manual,563276,INR,44011
11,https://www.cars24.com/buy-used-mg-hector-plus...,2022 MG HECTOR PLUS SELECT 2.0 DIESEL TURBO MT...,MG,HECTOR PLUS,2022,SUV,Diesel,Manual,1174000,INR,61224
12,https://www.cars24.com/buy-used-kia-sonet-2020...,2020 KIA SONET GTX PLUS 1.0 DCT DUAL TONE,KIA,SONET,2020,SUV,Petrol,Automatic,787840,INR,65337
13,https://www.cars24.com/buy-used-mahindra-xuv70...,2022 Mahindra XUV700 AX 5 P MT 5 STR,Mahindra,XUV700,2022,SUV,Petrol,Manual,1108100,INR,45924
14,https://www.cars24.com/buy-used-tata-indica-vi...,2014 Tata Indica Vista VX TECH QUADRAJET,Tata,Indica Vista,2014,Hatchback,Diesel,Manual,212936,INR,38245
15,https://www.cars24.com/buy-used-mahindra-xuv70...,2022 Mahindra XUV700 AX 3 P MT 5 STR,Mahindra,XUV700,2022,SUV,Petrol,Manual,1019197,INR,82103
16,https://www.cars24.com/buy-used-maruti-wagon-r...,2017 Maruti Wagon R 1.0 VXI AMT,Maruti,Wagon R 1.0,2017,Hatchback,Petrol,Automatic,388337,INR,14587
17,https://www.cars24.com/buy-used-hyundai-verna-...,2019 Hyundai Verna 1.6 VTVT SX,Hyundai,Verna,2019,Sedan,Petrol,Manual,646117,INR,70175
18,https://www.cars24.com/buy-used-datsun-redi-go...,2019 Datsun Redi Go S 1.0,Datsun,Redi Go,2019,Hatchback,Petrol,Manual,243614,INR,45340
19,https://www.cars24.com/buy-used-toyota-yaris-2...,2018 Toyota YARIS G CVT,Toyota,YARIS,2018,Sedan,Petrol,Automatic,523916,INR,74307
20,https://www.cars24.com/buy-used-renault-kwid-2...,2025 Renault Kwid RXL 1.0 (O),Renault,Kwid,2025,Hatchback,Petrol,Manual,468575,INR,3602
21,https://www.cars24.com/buy-used-maruti-swift-2...,2026 Maruti Swift VXi (O),Maruti,Swift,2026,Hatchback,Petrol,Manual,737140,INR,1051
22,https://www.cars24.com/buy-used-maruti-vitara-...,2022 Maruti Vitara Brezza VXI,Maruti,Vitara Brezza,2022,SUV,Petrol,Manual,736636,INR,80874
23,https://www.cars24.com/buy-used-hyundai-creta-...,2017 Hyundai Creta SX PLUS 1.6 PETROL,Hyundai,Creta,2017,SUV,Petrol,Manual,796000,INR,74994
24,https://www.cars24.com/buy-used-renault-kwid-2...,2019 Renault Kwid RXL,Renault,Kwid,2019,Hatchback,Petrol,Manual,297140,INR,43348
25,https://www.cars24.com/buy-used-maruti-swift-2...,2021 Maruti Swift VXI,Maruti,Swift,2021,Hatchback,Petrol,Manual,634282,INR,39447
26,https://www.cars24.com/buy-used-maruti-vitara-...,2022 Maruti Vitara Brezza VXI,Maruti,Vitara Brezza,2022,SUV,Petrol,Manual,708840,INR,95195
27,https://www.cars24.com/buy-used-maruti-ignis-2...,2021 Maruti IGNIS ZETA 1.2,Maruti,IGNIS,2021,Hatchback,Petrol,Manual,501115,INR,66919
28,https://www.cars24.com/buy-used-tata-nexon-202...,2021 Tata NEXON XZ PETROL,Tata,NEXON,2021,SUV,Petrol,Manual,725636,INR,44623
29,https://www.cars24.com/buy-used-tata-nexon-201...,2018 Tata NEXON XM PETROL,Tata,NEXON,2018,SUV,Petrol,Manual,582590,INR,78676
30,https://www.cars24.com/buy-used-ford-ecosport-...,2019 Ford Ecosport AMBIENTE 1.5L PETROL,Ford,Ecosport,2019,SUV,Petrol,Manual,556479,INR,48918
31,https://www.cars24.com/buy-used-renault-kwid-2...,2020 Renault Kwid RXT 1.0 (O),Renault,Kwid,2020,Hatchback,Petrol,Manual,326880,INR,39160
32,https://www.cars24.com/buy-used-kia-sonet-2022...,2022 KIA SONET HTK PLUS 1.0 IMT,KIA,SONET,2022,SUV,Petrol,Manual,728314,INR,45230
33,https://www.cars24.com/buy-used-maruti-alto-k1...,2014 Maruti Alto K10 VXI,Maruti,Alto K10,2014,Hatchback,Petrol,Manual,191140,INR,76242
34,https://www.cars24.com/buy-used-renault-kwid-2...,2024 Renault Kwid RXL(O) 1.0L AMT,Renault,Kwid,2024,Hatchback,Petrol,Automatic,486600,INR,1383
35,https://www.cars24.com/buy-used-renault-duster...,2020 Renault Duster RXE 1.3 TURBO PETROL MT,Renault,Duster,2020,SUV,Petrol,Manual,596456,INR,56880
36,https://www.cars24.com/buy-used-volkswagen-pol...,2019 Volkswagen Polo TRENDLINE 1.0L,Volkswagen,Polo,2019,Hatchback,Petrol,Manual,479854,INR,64701
37,https://www.cars24.com/buy-used-maruti-eeco-20...,2023 Maruti Eeco 5 STR AC,Maruti,Eeco,2023,SUV,Petrol,Manual,489940,INR,29921
38,https://www.cars24.com/buy-used-tata-nexon-202...,2023 Tata NEXON XM PETROL,Tata,NEXON,2023,SUV,Petrol,Manual,738636,INR,11287
39,https://www.cars24.com/buy-used-toyota-glanza-...,2022 Toyota Glanza V,Toyota,Glanza,2022,Hatchback,Petrol,Manual,718617,INR,69026

In [18]:
# Save our validated 40-record dataset

df_40.to_csv(
    "cars24_validated_40_raw.csv",
    index=False
)

print("Saved:", "cars24_validated_40_raw.csv")
print("Records:", len(df_40))
print("Columns:", len(df_40.columns))

Saved: cars24_validated_40_raw.csv
Records: 40
Columns: 11

In [19]:
import re
import asyncio
from playwright.async_api import async_playwright

CITY_URLS = {
    "Hyderabad": "https://www.cars24.com/buy-used-cars-hyderabad/",
    "Bangalore": "https://www.cars24.com/buy-used-cars-bangalore/",
    "Chennai": "https://www.cars24.com/buy-used-cars-chennai/",
    "Pune": "https://www.cars24.com/buy-used-cars-pune/",
    "Delhi": "https://www.cars24.com/buy-used-cars-delhi/",
    "Mumbai": "https://www.cars24.com/buy-used-cars-mumbai/",
    "Kolkata": "https://www.cars24.com/buy-used-cars-kolkata/",
    "Ahmedabad": "https://www.cars24.com/buy-used-cars-ahmedabad/",
    "Noida": "https://www.cars24.com/buy-used-cars-noida/",
    "Gurgaon": "https://www.cars24.com/buy-used-cars-gurgaon/"
}


def is_individual_listing(url):

    url = url.split("?")[0].rstrip("/")

    return bool(
        re.search(r"-\d{8,}$", url)
    )


async def collect_city_urls(page, city, city_url):

    print(f"\n========== {city} ==========")

    await page.goto(
        city_url,
        wait_until="domcontentloaded",
        timeout=60000
    )

    await page.wait_for_timeout(5000)

    # Scroll several times to load rendered content
    for i in range(10):

        await page.mouse.wheel(0, 4000)

        await page.wait_for_timeout(1500)

    links = await page.locator(
        "a[href]"
    ).evaluate_all(
        """els => els.map(a => a.href)"""
    )

    valid_urls = []

    for href in links:

        href = href.split("?")[0].rstrip("/")

        if is_individual_listing(href):

            valid_urls.append(
                href + "/"
            )

    valid_urls = list(
        dict.fromkeys(valid_urls)
    )

    print("Links found:", len(links))
    print("Valid listing URLs:", len(valid_urls))

    return valid_urls


async def collect_all_cities():

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=True
        )

        page = await browser.new_page(
            viewport={
                "width": 1440,
                "height": 900
            }
        )

        all_urls = {}

        for city, city_url in CITY_URLS.items():

            try:

                urls = await collect_city_urls(
                    page,
                    city,
                    city_url
                )

                all_urls[city] = urls

                await asyncio.sleep(2)

            except Exception as e:

                print(
                    f"ERROR in {city}: {e}"
                )

                all_urls[city] = []

        await browser.close()

        return all_urls


city_listing_urls = await collect_all_cities()


print("\n\n==============================")
print("FINAL URL COLLECTION")
print("==============================")

total = 0

for city, urls in city_listing_urls.items():

    print(
        f"{city}: {len(urls)} listings"
    )

    total += len(urls)

print("------------------------------")
print("TOTAL BEFORE DEDUP:", total)


# Combine all cities
all_listing_urls_2k = []

for urls in city_listing_urls.values():

    all_listing_urls_2k.extend(urls)


# Global deduplication
all_listing_urls_2k = list(
    dict.fromkeys(all_listing_urls_2k)
)

print(
    "TOTAL UNIQUE LISTING URLs:",
    len(all_listing_urls_2k)
)

========== Hyderabad ==========
Links found: 499
Valid listing URLs: 20

========== Bangalore ==========
Links found: 502
Valid listing URLs: 20

========== Chennai ==========
Links found: 464
Valid listing URLs: 20

========== Pune ==========
Links found: 489
Valid listing URLs: 20

========== Delhi ==========
Links found: 193
Valid listing URLs: 0

========== Mumbai ==========
Links found: 484
Valid listing URLs: 20

========== Kolkata ==========
Links found: 435
Valid listing URLs: 20

========== Ahmedabad ==========
Links found: 462
Valid listing URLs: 20

========== Noida ==========
Links found: 459
Valid listing URLs: 40

========== Gurgaon ==========
Links found: 477
Valid listing URLs: 40


==============================
FINAL URL COLLECTION
==============================
Hyderabad: 20 listings
Bangalore: 20 listings
Chennai: 20 listings
Pune: 20 listings
Delhi: 0 listings
Mumbai: 20 listings
Kolkata: 20 listings
Ahmedabad: 20 listings
Noida: 40 listings
Gurgaon: 40 listings
------------------------------
TOTAL BEFORE DEDUP: 220
TOTAL UNIQUE LISTING URLs: 194

In [20]:
# Save collected listing URLs

with open("cars24_listing_urls_194.txt", "w") as f:
    for url in all_listing_urls_2k:
        f.write(url + "\n")

print("Saved URLs:", len(all_listing_urls_2k))
print("File: cars24_listing_urls_194.txt")

Saved URLs: 194
File: cars24_listing_urls_194.txt

In [21]:
import re
import asyncio
from playwright.async_api import async_playwright

CATEGORY_URLS = {
    "Maruti": "https://www.cars24.com/buy-used-maruti-cars/",
    "Hyundai": "https://www.cars24.com/buy-used-hyundai-cars/",
    "Tata": "https://www.cars24.com/buy-used-tata-cars/",
    "Honda": "https://www.cars24.com/buy-used-honda-cars/",
    "Mahindra": "https://www.cars24.com/buy-used-mahindra-cars/",
    "Renault": "https://www.cars24.com/buy-used-renault-cars/",
    "Kia": "https://www.cars24.com/buy-used-kia-cars/",
    "Ford": "https://www.cars24.com/buy-used-ford-cars/",
    "Toyota": "https://www.cars24.com/buy-used-toyota-cars/",
    "Volkswagen": "https://www.cars24.com/buy-used-volkswagen-cars/"
}


def is_listing_url(url):

    url = url.split("?")[0].rstrip("/")

    return bool(
        re.search(r"-\d{8,}$", url)
    )


async def collect_category_urls(page, brand, category_url):

    print(f"\n========== {brand} ==========")

    await page.goto(
        category_url,
        wait_until="domcontentloaded",
        timeout=60000
    )

    await page.wait_for_timeout(5000)

    for i in range(10):

        await page.mouse.wheel(0, 4000)

        await page.wait_for_timeout(1500)

    links = await page.locator(
        "a[href]"
    ).evaluate_all(
        """els => els.map(a => a.href)"""
    )

    urls = []

    for href in links:

        href = href.split("?")[0].rstrip("/")

        if is_listing_url(href):

            urls.append(href + "/")

    urls = list(dict.fromkeys(urls))

    print("Links found:", len(links))
    print("Listing URLs:", len(urls))

    return urls


async def collect_categories():

    async with async_playwright() as p:

        browser = await p.chromium.launch(
            headless=True
        )

        page = await browser.new_page(
            viewport={
                "width": 1440,
                "height": 900
            }
        )

        results = {}

        for brand, url in CATEGORY_URLS.items():

            try:

                results[brand] = await collect_category_urls(
                    page,
                    brand,
                    url
                )

                await asyncio.sleep(2)

            except Exception as e:

                print(
                    f"ERROR in {brand}: {e}"
                )

                results[brand] = []

        await browser.close()

        return results


category_listing_urls = await collect_categories()


# Combine with our existing 194 URLs
expanded_urls = all_listing_urls_2k.copy()

for urls in category_listing_urls.values():
    expanded_urls.extend(urls)


# Remove duplicates
expanded_urls = list(
    dict.fromkeys(expanded_urls)
)


print("\n==============================")
print("EXPANDED COLLECTION")
print("==============================")

print(
    "Previous unique URLs:",
    len(all_listing_urls_2k)
)

print(
    "New unique URLs:",
    len(expanded_urls)
)

print(
    "New URLs discovered:",
    len(expanded_urls) - len(all_listing_urls_2k)
)

========== Maruti ==========
Links found: 444
Listing URLs: 20

========== Hyundai ==========
Links found: 444
Listing URLs: 20

========== Tata ==========
Links found: 444
Listing URLs: 20

========== Honda ==========
Links found: 444
Listing URLs: 20

========== Mahindra ==========
Links found: 443
Listing URLs: 20

========== Renault ==========
Links found: 443
Listing URLs: 20

========== Kia ==========
Links found: 445
Listing URLs: 20

========== Ford ==========
Links found: 443
Listing URLs: 20

========== Toyota ==========
Links found: 440
Listing URLs: 20

========== Volkswagen ==========
Links found: 443
Listing URLs: 20

==============================
EXPANDED COLLECTION
==============================
Previous unique URLs: 194
New unique URLs: 310
New URLs discovered: 116

In [22]:
from playwright.async_api import async_playwright
import re

BASE_URL = "https://www.cars24.com"

# Start with the URLs we already collected
all_urls = set(expanded_urls)

async def collect_from_page(page, url):
    try:
        await page.goto(url, wait_until="domcontentloaded", timeout=60000)
        await page.wait_for_timeout(3000)

        # Scroll more times to load available listings
        for _ in range(15):
            await page.mouse.wheel(0, 2500)
            await page.wait_for_timeout(1000)

        hrefs = await page.locator("a[href]").evaluate_all(
            """els => els.map(e => e.href).filter(Boolean)"""
        )

        listing_urls = set()

        for href in hrefs:
            clean = href.split("?")[0].rstrip("/")

            # Cars24 individual listing URL heuristic
            if re.search(r"-\d{8,}$", clean):
                listing_urls.add(clean + "/")

        return listing_urls

    except Exception as e:
        print("ERROR:", url, "|", e)
        return set()


async def main():
    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        # Known Cars24 category/filter pages
        pages_to_check = [
            "https://www.cars24.com/buy-used-cars-hyderabad/",
            "https://www.cars24.com/buy-used-cars-bangalore/",
            "https://www.cars24.com/buy-used-cars-chennai/",
            "https://www.cars24.com/buy-used-cars-pune/",
            "https://www.cars24.com/buy-used-cars-mumbai/",
            "https://www.cars24.com/buy-used-cars-kolkata/",
            "https://www.cars24.com/buy-used-cars-ahmedabad/",
            "https://www.cars24.com/buy-used-cars-noida/",
            "https://www.cars24.com/buy-used-cars-gurgaon/",

            "https://www.cars24.com/buy-used-maruti-cars/",
            "https://www.cars24.com/buy-used-hyundai-cars/",
            "https://www.cars24.com/buy-used-tata-cars/",
            "https://www.cars24.com/buy-used-honda-cars/",
            "https://www.cars24.com/buy-used-mahindra-cars/",
            "https://www.cars24.com/buy-used-renault-cars/",
            "https://www.cars24.com/buy-used-kia-cars/",
            "https://www.cars24.com/buy-used-ford-cars/",
            "https://www.cars24.com/buy-used-toyota-cars/",
            "https://www.cars24.com/buy-used-volkswagen-cars/",
        ]

        before = len(all_urls)

        for url in pages_to_check:
            print("\nChecking:", url)

            found = await collect_from_page(page, url)

            new_urls = found - all_urls
            all_urls.update(found)

            print("Found:", len(found))
            print("New:", len(new_urls))
            print("Total unique:", len(all_urls))

            if len(all_urls) >= 2000:
                print("\n🎯 TARGET REACHED:", len(all_urls))
                break

        await browser.close()

    print("\n==============================")
    print("FINAL URL COLLECTION")
    print("==============================")
    print("Previous:", before)
    print("New:", len(all_urls) - before)
    print("Total unique:", len(all_urls))

    with open("cars24_listing_urls_expanded.txt", "w") as f:
        for url in sorted(all_urls):
            f.write(url + "\n")

    print("Saved: cars24_listing_urls_expanded.txt")


await main()

# Keep variable available for next cells
expanded_urls = all_urls

Checking: https://www.cars24.com/buy-used-cars-hyderabad/
Found: 100
New: 80
Total unique: 390

Checking: https://www.cars24.com/buy-used-cars-bangalore/
Found: 100
New: 70
Total unique: 460

Checking: https://www.cars24.com/buy-used-cars-chennai/
Found: 100
New: 80
Total unique: 540

Checking: https://www.cars24.com/buy-used-cars-pune/
Found: 100
New: 78
Total unique: 618

Checking: https://www.cars24.com/buy-used-cars-mumbai/
Found: 100
New: 80
Total unique: 698

Checking: https://www.cars24.com/buy-used-cars-kolkata/
Found: 100
New: 77
Total unique: 775

Checking: https://www.cars24.com/buy-used-cars-ahmedabad/
Found: 100
New: 73
Total unique: 848

Checking: https://www.cars24.com/buy-used-cars-noida/
Found: 160
New: 101
Total unique: 949

Checking: https://www.cars24.com/buy-used-cars-gurgaon/
Found: 160
New: 80
Total unique: 1029

Checking: https://www.cars24.com/buy-used-maruti-cars/
Found: 40
New: 7
Total unique: 1036

Checking: https://www.cars24.com/buy-used-hyundai-cars/
Found: 40
New: 13
Total unique: 1049

Checking: https://www.cars24.com/buy-used-tata-cars/
Found: 40
New: 11
Total unique: 1060

Checking: https://www.cars24.com/buy-used-honda-cars/
Found: 40
New: 9
Total unique: 1069

Checking: https://www.cars24.com/buy-used-mahindra-cars/
Found: 40
New: 11
Total unique: 1080

Checking: https://www.cars24.com/buy-used-renault-cars/
Found: 40
New: 6
Total unique: 1086

Checking: https://www.cars24.com/buy-used-kia-cars/
Found: 40
New: 10
Total unique: 1096

Checking: https://www.cars24.com/buy-used-ford-cars/
Found: 40
New: 12
Total unique: 1108

Checking: https://www.cars24.com/buy-used-toyota-cars/
Found: 40
New: 11
Total unique: 1119

Checking: https://www.cars24.com/buy-used-volkswagen-cars/
Found: 40
New: 13
Total unique: 1132

==============================
FINAL URL COLLECTION
==============================
Previous: 310
New: 822
Total unique: 1132
Saved: cars24_listing_urls_expanded.txt

In [23]:
MORE_CITY_URLS = {
    "Jaipur": "https://www.cars24.com/buy-used-cars-jaipur/",
    "Lucknow": "https://www.cars24.com/buy-used-cars-lucknow/",
    "Chandigarh": "https://www.cars24.com/buy-used-cars-chandigarh/",
    "Indore": "https://www.cars24.com/buy-used-cars-indore/",
    "Surat": "https://www.cars24.com/buy-used-cars-surat/",
    "Kochi": "https://www.cars24.com/buy-used-cars-kochi/",
    "Coimbatore": "https://www.cars24.com/buy-used-cars-coimbatore/",
    "Nagpur": "https://www.cars24.com/buy-used-cars-nagpur/",
    "Patna": "https://www.cars24.com/buy-used-cars-patna/",
    "Bhopal": "https://www.cars24.com/buy-used-cars-bhopal/",
    "Vadodara": "https://www.cars24.com/buy-used-cars-vadodara/",
    "Nashik": "https://www.cars24.com/buy-used-cars-nashik/",
}

async def collect_more_cities():

    async with async_playwright() as p:
        browser = await p.chromium.launch(headless=True)
        page = await browser.new_page()

        before = len(expanded_urls)

        for city, url in MORE_CITY_URLS.items():

            print(f"\n========== {city} ==========")

            found = await collect_from_page(page, url)

            new_urls = found - expanded_urls

            expanded_urls.update(found)

            print("Found:", len(found))
            print("New:", len(new_urls))
            print("Total unique:", len(expanded_urls))

            if len(expanded_urls) >= 2000:
                print("\n🎯 2000+ TARGET REACHED!")
                break

        await browser.close()

    print("\n==============================")
    print("UPDATED URL COLLECTION")
    print("==============================")
    print("Previous:", before)
    print("New:", len(expanded_urls) - before)
    print("Total unique:", len(expanded_urls))

    with open("cars24_listing_urls_2000_target.txt", "w") as f:
        for url in sorted(expanded_urls):
            f.write(url + "\n")

    print("Saved: cars24_listing_urls_2000_target.txt")


await collect_more_cities()

========== Jaipur ==========
Found: 100
New: 85
Total unique: 1217

========== Lucknow ==========
Found: 100
New: 80
Total unique: 1297

========== Chandigarh ==========
Found: 147
New: 133
Total unique: 1430

========== Indore ==========
Found: 100
New: 83
Total unique: 1513

========== Surat ==========
Found: 100
New: 90
Total unique: 1603

========== Kochi ==========
Found: 100
New: 81
Total unique: 1684

========== Coimbatore ==========
Found: 100
New: 83
Total unique: 1767

========== Nagpur ==========
Found: 40
New: 40
Total unique: 1807

========== Patna ==========
Found: 100
New: 83
Total unique: 1890

========== Bhopal ==========
Found: 100
New: 91
Total unique: 1981

========== Vadodara ==========
Found: 100
New: 89
Total unique: 2070

🎯 2000+ TARGET REACHED!

==============================
UPDATED URL COLLECTION
==============================
Previous: 1132
New: 938
Total unique: 2070
Saved: cars24_listing_urls_2000_target.txt

In [24]:
import json
import pandas as pd
from datetime import datetime
from playwright.async_api import async_playwright

# Load collected URLs
with open("cars24_listing_urls_2000_target.txt", "r") as f:
    listing_urls = [line.strip() for line in f if line.strip()]

print("Total URLs loaded:", len(listing_urls))


def find_car_jsonld(json_data):
    """Find Car object inside JSON-LD."""
    if isinstance(json_data, dict):
        if json_data.get("@type") == "Car":
            return json_data

        for value in json_data.values():
            result = find_car_jsonld(value)
            if result:
                return result

    elif isinstance(json_data, list):
        for item in json_data:
            result = find_car_jsonld(item)
            if result:
                return result

    return None


def get_nested(data, *keys):
    """Safely read nested JSON fields."""
    current = data

    for key in keys:
        if not isinstance(current, dict):
            return None
        current = current.get(key)

    return current


async def extract_car(page, url):

    try:
        await page.goto(
            url,
            wait_until="domcontentloaded",
            timeout=60000
        )

        await page.wait_for_timeout(1500)

        scripts = page.locator('script[type="application/ld+json"]')

        count = await scripts.count()

        car = None

        for i in range(count):

            text = await scripts.nth(i).text_content()

            if not text:
                continue

            try:
                data = json.loads(text)
                car = find_car_jsonld(data)

                if car:
                    break

            except:
                continue

        if not car:
            return None

        offers = car.get("offers", {})

        mileage = car.get("mileageFromOdometer", {})

        brand = car.get("brand")

        if isinstance(brand, dict):
            brand = brand.get("name")

        record = {

            "listing_url": url,

            "car_name": car.get("name"),

            "brand": brand,

            "model": car.get("model"),

            "manufacturing_year":
                car.get("vehicleModelDate"),

            "body_type":
                car.get("bodyType"),

            "fuel_type":
                car.get("fuelType"),

            "transmission":
                car.get("vehicleTransmission"),

            "price_numeric":
                offers.get("price")
                if isinstance(offers, dict)
                else None,

            "price_currency":
                offers.get("priceCurrency")
                if isinstance(offers, dict)
                else None,

            "km_driven":
                mileage.get("value")
                if isinstance(mileage, dict)
                else None,

            "source_website": "Cars24",

            "scraped_date":
                datetime.now().strftime("%Y-%m-%d")
        }

        return record

    except Exception as e:

        print("FAILED:", url)
        print("Reason:", str(e)[:150])

        return None


async def test_scrape():

    records = []

    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page()

        # ONLY FIRST 20 FOR TESTING
        test_urls = listing_urls[:20]

        for i, url in enumerate(test_urls, start=1):

            print(f"[{i}/{len(test_urls)}] Scraping...")

            record = await extract_car(page, url)

            if record:

                records.append(record)

                print(
                    "OK:",
                    record["car_name"],
                    "| ₹",
                    record["price_numeric"]
                )

            else:

                print("NO DATA")

        await browser.close()

    df_test = pd.DataFrame(records)

    df_test.to_csv(
        "cars24_20_scrape_test.csv",
        index=False
    )

    print("\n============================")
    print("TEST COMPLETE")
    print("============================")

    print("URLs tested:", len(test_urls))
    print("Successful:", len(df_test))
    print("Failed:", len(test_urls) - len(df_test))

    print("\nSaved: cars24_20_scrape_test.csv")

    return df_test


df_test = await test_scrape()

df_test

Total URLs loaded: 2070
[1/20] Scraping...
OK: 2021 Audi A4 40 TFSI TECHNOLOGY | ₹ 2524340
[2/20] Scraping...
OK: 2024 Audi A4 40 TFSI  PREMIUM PLUS | ₹ 3121340
[3/20] Scraping...
OK: 2014 Audi A6 2.0 TDI PREMIUM PLUS | ₹ 594500
[4/20] Scraping...
OK: 2019 Audi Q5 40 TDI PREMIUM PLUS | ₹ 2675340
[5/20] Scraping...
OK: 2014 BMW X1 SDRIVE 20D X LINE | ₹ 760000
[6/20] Scraping...
OK: 2020 BMW X1 SDrive20i Xline | ₹ 2096994
[7/20] Scraping...
OK: 2022 BMW X1 SDRIVE 20i SPORTX | ₹ 3349000
[8/20] Scraping...
OK: 2012 Chevrolet Beat LT PETROL | ₹ 90000
[9/20] Scraping...
OK: 2014 Chevrolet Beat LS PETROL | ₹ 133140
[10/20] Scraping...
OK: 2013 Chevrolet Cruze LTZ AT | ₹ 374597
[11/20] Scraping...
OK: 2013 Chevrolet Sail 1.2 LS ABS | ₹ 189140
[12/20] Scraping...
OK: 2013 Chevrolet Sail 1.2 LS ABS | ₹ 129936
[13/20] Scraping...
OK: 2014 Chevrolet Sail 1.2 LS | ₹ 161981
[14/20] Scraping...
OK: 2013 Chevrolet Sail UVA 1.2 BASE | ₹ 221936
[15/20] Scraping...
OK: 2022 CITROEN C3 FEEL 1.2 | ₹ 408227
[16/20] Scraping...
OK: 2026 CITROEN C3 SHINE 1.2 | ₹ 739094
[17/20] Scraping...
OK: 2017 Datsun Go ANNIVERSARY EDITION | ₹ 175140
[18/20] Scraping...
OK: 2017 Datsun Go T | ₹ 194996
[19/20] Scraping...
OK: 2018 Datsun Go T | ₹ 227140
[20/20] Scraping...
OK: 2019 Datsun Go A(O) | ₹ 231140

============================
TEST COMPLETE
============================
URLs tested: 20
Successful: 20
Failed: 0

Saved: cars24_20_scrape_test.csv

,listing_url,car_name,brand,model,manufacturing_year,body_type,fuel_type,transmission,price_numeric,price_currency,km_driven,source_website,scraped_date
0,https://www.cars24.com/buy-used-audi-a4-2021-c...,2021 Audi A4 40 TFSI TECHNOLOGY,Audi,A4,2021,Sedan,Petrol,Automatic,2524340,INR,62836,Cars24,2026-09-21
1,https://www.cars24.com/buy-used-audi-a4-2024-c...,2024 Audi A4 40 TFSI PREMIUM PLUS,Audi,A4,2024,Sedan,Petrol,Automatic,3121340,INR,11198,Cars24,2026-09-21
2,https://www.cars24.com/buy-used-audi-a6-2014-c...,2014 Audi A6 2.0 TDI PREMIUM PLUS,Audi,A6,2014,Sedan,Diesel,Automatic,594500,INR,110048,Cars24,2026-09-21
3,https://www.cars24.com/buy-used-audi-q5-2019-c...,2019 Audi Q5 40 TDI PREMIUM PLUS,Audi,Q5,2019,SUV,Diesel,Automatic,2675340,INR,77788,Cars24,2026-09-21
4,https://www.cars24.com/buy-used-bmw-x1-2014-ca...,2014 BMW X1 SDRIVE 20D X LINE,BMW,X1,2014,SUV,Diesel,Automatic,760000,INR,99855,Cars24,2026-09-21
5,https://www.cars24.com/buy-used-bmw-x1-2020-ca...,2020 BMW X1 SDrive20i Xline,BMW,X1,2020,SUV,Petrol,Automatic,2096994,INR,58334,Cars24,2026-09-21
6,https://www.cars24.com/buy-used-bmw-x1-2022-ca...,2022 BMW X1 SDRIVE 20i SPORTX,BMW,X1,2022,SUV,Petrol,Automatic,3349000,INR,82679,Cars24,2026-09-21
7,https://www.cars24.com/buy-used-chevrolet-beat...,2012 Chevrolet Beat LT PETROL,Chevrolet,Beat,2012,Hatchback,Petrol,Manual,90000,INR,47972,Cars24,2026-09-21
8,https://www.cars24.com/buy-used-chevrolet-beat...,2014 Chevrolet Beat LS PETROL,Chevrolet,Beat,2014,Hatchback,Petrol,Manual,133140,INR,78601,Cars24,2026-09-21
9,https://www.cars24.com/buy-used-chevrolet-cruz...,2013 Chevrolet Cruze LTZ AT,Chevrolet,Cruze,2013,Sedan,Diesel,Automatic,374597,INR,111286,Cars24,2026-09-21
10,https://www.cars24.com/buy-used-chevrolet-sail...,2013 Chevrolet Sail 1.2 LS ABS,Chevrolet,Sail,2013,Sedan,Petrol,Manual,189140,INR,43669,Cars24,2026-09-21
11,https://www.cars24.com/buy-used-chevrolet-sail...,2013 Chevrolet Sail 1.2 LS ABS,Chevrolet,Sail,2013,Sedan,Petrol,Manual,129936,INR,69350,Cars24,2026-09-21
12,https://www.cars24.com/buy-used-chevrolet-sail...,2014 Chevrolet Sail 1.2 LS,Chevrolet,Sail,2014,Sedan,Petrol,Manual,161981,INR,28070,Cars24,2026-09-21
13,https://www.cars24.com/buy-used-chevrolet-sail...,2013 Chevrolet Sail UVA 1.2 BASE,Chevrolet,Sail UVA,2013,Hatchback,Petrol,Manual,221936,INR,52781,Cars24,2026-09-21
14,https://www.cars24.com/buy-used-citroen-c3-202...,2022 CITROEN C3 FEEL 1.2,CITROEN,C3,2022,Hatchback,CNG,Manual,408227,INR,71565,Cars24,2026-09-21
15,https://www.cars24.com/buy-used-citroen-c3-202...,2026 CITROEN C3 SHINE 1.2,CITROEN,C3,2026,Hatchback,Petrol,Manual,739094,INR,28680,Cars24,2026-09-21
16,https://www.cars24.com/buy-used-datsun-go-2017...,2017 Datsun Go ANNIVERSARY EDITION,Datsun,Go,2017,Hatchback,Petrol,Manual,175140,INR,40573,Cars24,2026-09-21
17,https://www.cars24.com/buy-used-datsun-go-2017...,2017 Datsun Go T,Datsun,Go,2017,Hatchback,CNG,Manual,194996,INR,123084,Cars24,2026-09-21
18,https://www.cars24.com/buy-used-datsun-go-2018...,2018 Datsun Go T,Datsun,Go,2018,Hatchback,Petrol,Manual,227140,INR,86045,Cars24,2026-09-21
19,https://www.cars24.com/buy-used-datsun-go-2019...,2019 Datsun Go A(O),Datsun,Go,2019,Hatchback,Petrol,Manual,231140,INR,65179,Cars24,2026-09-21

In [25]:
import os
import pandas as pd
from datetime import datetime
from playwright.async_api import async_playwright

# Load all URLs
with open("cars24_listing_urls_2000_target.txt", "r") as f:
    listing_urls = [line.strip() for line in f if line.strip()]

print("Total URLs:", len(listing_urls))

CHECKPOINT_FILE = "cars24_raw_checkpoint.csv"
FINAL_FILE = "cars24_raw_2070.csv"

# Resume if checkpoint already exists
if os.path.exists(CHECKPOINT_FILE):
    old_df = pd.read_csv(CHECKPOINT_FILE)
    scraped_urls = set(old_df["listing_url"].astype(str))

    records = old_df.to_dict("records")

    print("Existing checkpoint:", len(records))
    print("Remaining:", len(listing_urls) - len(scraped_urls))

else:
    records = []
    scraped_urls = set()

    print("Starting fresh scrape")


async def scrape_all():

    async with async_playwright() as p:

        browser = await p.chromium.launch(headless=True)

        page = await browser.new_page()

        remaining_urls = [
            url for url in listing_urls
            if url not in scraped_urls
        ]

        total_remaining = len(remaining_urls)

        for index, url in enumerate(remaining_urls, start=1):

            try:

                record = await extract_car(page, url)

                if record:

                    records.append(record)
                    scraped_urls.add(url)

                    print(
                        f"[{index}/{total_remaining}] "
                        f"OK | {record['car_name']}"
                    )

                else:

                    print(
                        f"[{index}/{total_remaining}] "
                        f"NO DATA"
                    )

            except Exception as e:

                print(
                    f"[{index}/{total_remaining}] "
                    f"ERROR | {str(e)[:100]}"
                )

            # Save checkpoint every 50 records
            if len(records) % 50 == 0 and len(records) > 0:

                checkpoint_df = pd.DataFrame(records)

                checkpoint_df.to_csv(
                    CHECKPOINT_FILE,
                    index=False
                )

                print(
                    f"\n💾 CHECKPOINT SAVED: "
                    f"{len(records)} records\n"
                )

        await browser.close()


await scrape_all()


# Final dataframe
df_raw = pd.DataFrame(records)

# Remove duplicate listing URLs
df_raw = df_raw.drop_duplicates(
    subset=["listing_url"]
).reset_index(drop=True)

# Save final raw dataset
df_raw.to_csv(
    FINAL_FILE,
    index=False
)

print("\n================================")
print("FULL SCRAPE COMPLETE")
print("================================")

print("Total URLs:", len(listing_urls))
print("Raw records:", len(df_raw))
print("Unique records:", df_raw["listing_url"].nunique())
print("Columns:", len(df_raw.columns))

print("\nSaved:")
print(FINAL_FILE)

print("\nData preview:")
display(df_raw.head())

Total URLs: 2070
Starting fresh scrape
[1/2070] OK | 2021 Audi A4 40 TFSI TECHNOLOGY
[2/2070] OK | 2024 Audi A4 40 TFSI  PREMIUM PLUS
[3/2070] OK | 2014 Audi A6 2.0 TDI PREMIUM PLUS
[4/2070] OK | 2019 Audi Q5 40 TDI PREMIUM PLUS
[5/2070] OK | 2014 BMW X1 SDRIVE 20D X LINE
[6/2070] OK | 2020 BMW X1 SDrive20i Xline
[7/2070] OK | 2022 BMW X1 SDRIVE 20i SPORTX
[8/2070] OK | 2012 Chevrolet Beat LT PETROL
[9/2070] OK | 2014 Chevrolet Beat LS PETROL
[10/2070] OK | 2013 Chevrolet Cruze LTZ AT
[11/2070] OK | 2013 Chevrolet Sail 1.2 LS ABS
[12/2070] OK | 2013 Chevrolet Sail 1.2 LS ABS
[13/2070] OK | 2014 Chevrolet Sail 1.2 LS
[14/2070] OK | 2013 Chevrolet Sail UVA 1.2 BASE
[15/2070] OK | 2022 CITROEN C3 FEEL 1.2
[16/2070] OK | 2026 CITROEN C3 SHINE 1.2
[17/2070] OK | 2017 Datsun Go ANNIVERSARY EDITION
[18/2070] OK | 2017 Datsun Go T
[19/2070] OK | 2018 Datsun Go T
[20/2070] OK | 2019 Datsun Go A(O)
[21/2070] OK | 2015 Datsun Go Plus T
[22/2070] OK | 2015 Datsun Go Plus T
[23/2070] OK | 2018 Datsun Go Plus T
[24/2070] OK | 2016 Datsun Redi Go S
[25/2070] OK | 2016 Datsun Redi Go S
[26/2070] OK | 2016 Datsun Redi Go T
[27/2070] OK | 2016 Datsun Redi Go S
[28/2070] OK | 2017 Datsun Redi Go T (O)
[29/2070] OK | 2017 Datsun Redi Go S
[30/2070] OK | 2017 Datsun Redi Go T
[31/2070] OK | 2017 Datsun Redi Go T(O) 1.0
[32/2070] OK | 2017 Datsun Redi Go T(O) 1.0
[33/2070] OK | 2017 Datsun Redi Go T(O) 1.0
[34/2070] OK | 2017 Datsun Redi Go A
[35/2070] OK | 2017 Datsun Redi Go T(O) 1.0
[36/2070] OK | 2018 Datsun Redi Go T(O) 1.0
[37/2070] OK | 2018 Datsun Redi Go T(O) 1.0
[38/2070] OK | 2018 Datsun Redi Go T (O)
[39/2070] OK | 2018 Datsun Redi Go D
[40/2070] OK | 2018 Datsun Redi Go S
[41/2070] OK | 2018 Datsun Redi Go T (O)
[42/2070] OK | 2018 Datsun Redi Go A
[43/2070] OK | 2018 Datsun Redi Go A
[44/2070] OK | 2018 Datsun Redi Go T(O) 1.0
[45/2070] OK | 2018 Datsun Redi Go T(O) 1.0
[46/2070] OK | 2018 Datsun Redi Go T (O)
[47/2070] OK | 2018 Datsun Redi Go T (O)
[48/2070] OK | 2018 Datsun Redi Go GOLD LIMITED EDITION
[49/2070] OK | 2018 Datsun Redi Go T(O) 1.0
[50/2070] OK | 2018 Datsun Redi Go T(O) 1.0L LIMITED EDITION

💾 CHECKPOINT SAVED: 50 records

[51/2070] OK | 2019 Datsun Redi Go S 1.0 AMT
[52/2070] OK | 2019 Datsun Redi Go T (O)
[53/2070] OK | 2019 Datsun Redi Go S 1.0 AMT
[54/2070] OK | 2019 Datsun Redi Go S
[55/2070] OK | 2019 Datsun Redi Go S 1.0
[56/2070] OK | 2019 Datsun Redi Go S 1.0 AMT
[57/2070] OK | 2019 Datsun Redi Go A
[58/2070] OK | 2020 Datsun Redi Go T(O) 0.8L LIMITED EDITION
[59/2070] OK | 2020 Datsun Redi Go T(O) 1.0 AMT
[60/2070] OK | 2021 Datsun Redi Go T
[61/2070] OK | 2021 Datsun Redi Go T(O)
[62/2070] OK | 2021 Datsun Redi Go T
[63/2070] OK | 2021 Datsun Redi Go T(O) 1.0
[64/2070] OK | 2017 Fiat Linea EMOTION 1.4 L T JET 125S
[65/2070] OK | 2017 Fiat Linea EMOTION 1.4 L T JET 125S
[66/2070] OK | 2018 Fiat URBAN CROSS EMOTION MULTIJET 1.3
[67/2070] OK | 2013 Ford Ecosport TITANIUM 1.5L PETROL AT
[68/2070] OK | 2013 Ford Ecosport TREND 1.5L PETROL
[69/2070] OK | 2013 Ford Ecosport TREND 1.5L DIESEL
[70/2070] OK | 2013 Ford Ecosport TREND 1.5L DIESEL
[71/2070] OK | 2014 Ford Ecosport TITANIUM 1.5L DIESEL
[72/2070] OK | 2014 Ford Ecosport AMBIENTE 1.5L DIESEL
[73/2070] OK | 2014 Ford Ecosport TITANIUM 1.5L PETROL AT
[74/2070] OK | 2014 Ford Ecosport TREND 1.5L PETROL
[75/2070] OK | 2014 Ford Ecosport TITANIUM 1.5L PETROL AT
[76/2070] OK | 2015 Ford Ecosport TITANIUM 1.5L PETROL AT
[77/2070] OK | 2015 Ford Ecosport TITANIUM 1.0L ECOBOOST
[78/2070] OK | 2015 Ford Ecosport TITANIUM 1.0L ECOBOOST
[79/2070] OK | 2015 Ford Ecosport TREND 1.5L PETROL
[80/2070] OK | 2015 Ford Ecosport TITANIUM 1.5L DIESEL
[81/2070] OK | 2015 Ford Ecosport TITANIUM 1.0L ECOBOOST
[82/2070] OK | 2015 Ford Ecosport TITANIUM 1.5L PETROL
[83/2070] OK | 2015 Ford Ecosport TITANIUM 1.5L PETROL
[84/2070] OK | 2015 Ford Ecosport AMBIENTE 1.5L PETROL
[85/2070] OK | 2016 Ford Ecosport AMBIENTE 1.5L DIESEL
[86/2070] OK | 2016 Ford Ecosport TREND 1.5L PETROL
[87/2070] OK | 2016 Ford Ecosport TITANIUM 1.5L PETROL
[88/2070] OK | 2016 Ford Ecosport TREND 1.5L DIESEL
[89/2070] OK | 2017 Ford Ecosport TITANIUM+ 1.0L ECOBOOST
[90/2070] OK | 2017 Ford Ecosport TITANIUM 1.5L DIESEL
[91/2070] OK | 2017 Ford Ecosport TREND 1.5L PETROL
[92/2070] OK | 2017 Ford Ecosport TITANIUM 1.5L DIESEL
[93/2070] OK | 2017 Ford Ecosport TREND 1.5L PETROL
[94/2070] OK | 2017 Ford Ecosport TREND+ 1.0L ECOBOOST
[95/2070] OK | 2017 Ford Ecosport AMBIENTE 1.5L PETROL
[96/2070] OK | 2018 Ford Ecosport TITANIUM 1.0L ECOBOOST SPORTS(SUNROOF)
[97/2070] OK | 2018 Ford Ecosport TITANIUM 1.5L DIESEL
[98/2070] OK | 2018 Ford Ecosport TITANIUM 1.5L DIESEL
[99/2070] OK | 2018 Ford Ecosport TITANIUM 1.5L PETROL
[100/2070] OK | 2018 Ford Ecosport TREND + 1.5L PETROL AT

💾 CHECKPOINT SAVED: 100 records

[101/2070] OK | 2019 Ford Ecosport TITANIUM 1.5L PETROL
[102/2070] OK | 2019 Ford Ecosport TITANIUM 1.5L PETROL
[103/2070] OK | 2019 Ford Ecosport AMBIENTE 1.5L PETROL
[104/2070] OK | 2019 Ford Ecosport AMBIENTE 1.5L PETROL
[105/2070] OK | 2019 Ford Ecosport TITANIUM 1.0L ECOBOOST SPORTS(SUNROOF)
[106/2070] OK | 2019 Ford Ecosport TITANIUM 1.5L PETROL
[107/2070] OK | 2019 Ford Ecosport TITANIUM + 1.5L PETROL AT
[108/2070] OK | 2019 Ford Ecosport TITANIUM 1.5L THUNDER EDTION PETROL
[109/2070] OK | 2019 Ford Ecosport TITANIUM 1.5L PETROL
[110/2070] OK | 2019 Ford Ecosport TITANIUM 1.5L PETROL
[111/2070] OK | 2019 Ford Ecosport TITANIUM 1.0L ECOBOOST SPORTS(SUNROOF)
[112/2070] OK | 2019 Ford Ecosport TITANIUM 1.5 SPORTS(SUNROOF) PETROL
[113/2070] OK | 2019 Ford Ecosport TITANIUM + 1.5L PETROL AT
[114/2070] OK | 2019 Ford Ecosport TITANIUM + 1.5L PETROL AT
[115/2070] OK | 2019 Ford Ecosport AMBIENTE 1.5L PETROL
[116/2070] OK | 2020 Ford Ecosport TITANIUM 1.5 SPORTS(SUNROOF) PETROL
[117/2070] OK | 2020 Ford Ecosport AMBIENTE 1.5L PETROL
[118/2070] OK | 2020 Ford Ecosport TITANIUM 1.5L PETROL
[119/2070] OK | 2020 Ford Ecosport TREND 1.5L PETROL
[120/2070] OK | 2020 Ford Ecosport TITANIUM 1.5L DIESEL
[121/2070] OK | 2020 Ford Ecosport AMBIENTE 1.5L PETROL
[122/2070] OK | 2020 Ford Ecosport TITANIUM 1.5L PETROL
[123/2070] OK | 2020 Ford Ecosport TITANIUM + 1.5L PETROL AT
[124/2070] OK | 2020 Ford Ecosport TITANIUM 1.5L PETROL
[125/2070] OK | 2021 Ford Ecosport TITANIUM + 1.5L PETROL AT
[126/2070] OK | 2010 Ford Endeavour 2.5L 4X2 MT
[127/2070] OK | 2020 Ford Endeavour TITANIUM PLUS 2.0 4X4 AT SUNROOF
[128/2070] OK | 2015 Ford Figo Aspire AMBIENTE 1.5 DIESEL
[129/2070] OK | 2015 Ford Figo Aspire TITANIUM1.5 DIESEL
[130/2070] OK | 2015 Ford Figo Aspire TREND 1.2 PETROL
[131/2070] OK | 2016 Ford Figo Aspire AMBIENTE 1.2 PETROL ABS
[132/2070] OK | 2017 Ford Figo Aspire TITANIUM 1.2 PETROL
[133/2070] OK | 2018 Ford Figo Aspire TITANIUM 1.2 PETROL
[134/2070] OK | 2019 Ford Figo Aspire TITANIUM1.5 DIESEL
[135/2070] OK | 2020 Ford Figo Aspire TITANIUM 1.2 PETROL
[136/2070] OK | 2020 Ford Figo Aspire TITANIUM PLUS 1.2 PETROL
[137/2070] OK | 2021 Ford Figo Aspire TITANIUM 1.2 PETROL
[138/2070] OK | 2021 Ford Figo Aspire TITANIUM PLUS 1.2 PETROL
[139/2070] OK | 2018 Ford FREESTYLE TITANIUM PLUS 1.5 DIESEL
[140/2070] OK | 2018 Ford FREESTYLE TITANIUM 1.5 DIESEL
[141/2070] OK | 2019 Ford FREESTYLE TITANIUM 1.2 PETROL
[142/2070] OK | 2021 Ford FREESTYLE TITANIUM PLUS 1.2 PETROL
[143/2070] OK | 2017 Ford New Figo TREND 1.2 PETROL
[144/2070] OK | 2021 Ford New Figo TITANIUM 1.2 PETROL MT
[145/2070] OK | 2013 Honda Amaze 1.2L I-VTEC EX
[146/2070] OK | 2014 Honda Amaze 1.2L I-VTEC SX
[147/2070] OK | 2014 Honda Amaze 1.2L I-VTEC VX AT
[148/2070] OK | 2014 Honda Amaze 1.2L I-VTEC SX
[149/2070] OK | 2014 Honda Amaze 1.2L I-VTEC E
[150/2070] OK | 2014 Honda Amaze 1.5L I-DTEC E

💾 CHECKPOINT SAVED: 150 records

[151/2070] OK | 2015 Honda Amaze 1.2L I-VTEC S
[152/2070] OK | 2015 Honda Amaze 1.2L I-VTEC VX
[153/2070] OK | 2015 Honda Amaze 1.2L I-VTEC S
[154/2070] OK | 2015 Honda Amaze 1.5L I-DTEC E
[155/2070] OK | 2015 Honda Amaze 1.2L I-VTEC VX
[156/2070] OK | 2016 Honda Amaze 1.2L I-VTEC SX
[157/2070] OK | 2016 Honda Amaze 1.2L I-VTEC S
[158/2070] OK | 2016 Honda Amaze 1.2L I-VTEC SX
[159/2070] OK | 2016 Honda Amaze 1.2L I-VTEC VX
[160/2070] OK | 2016 Honda Amaze 1.2L I-VTEC S
[161/2070] OK | 2016 Honda Amaze 1.2L I-VTEC S
[162/2070] OK | 2016 Honda Amaze 1.2L I-VTEC S
[163/2070] OK | 2017 Honda Amaze 1.2L I-VTEC S OPT
[164/2070] OK | 2018 Honda Amaze 1.2L I-VTEC VX
[165/2070] OK | 2019 Honda Amaze 1.2L I-VTEC VX
[166/2070] OK | 2019 Honda Amaze 1.2L I-VTEC VX CVT
[167/2070] OK | 2019 Honda Amaze 1.2L I-VTEC S CVT
[168/2070] OK | 2019 Honda Amaze 1.2L I-VTEC E
[169/2070] OK | 2019 Honda Amaze 1.2L I-VTEC V
[170/2070] OK | 2019 Honda Amaze 1.2L I-VTEC VX
[171/2070] OK | 2019 Honda Amaze 1.2L I-VTEC V
[172/2070] OK | 2021 Honda Amaze 1.2L I-VTEC S
[173/2070] OK | 2021 Honda Amaze 1.2L I-VTEC S
[174/2070] OK | 2021 Honda Amaze 1.2L I-VTEC VX CVT
[175/2070] OK | 2022 Honda Amaze 1.2L I-VTEC VX CVT
[176/2070] OK | 2023 Honda Amaze 1.2L I-VTEC VX
[177/2070] OK | 2024 Honda Amaze 1.2L I-VTEC VX
[178/2070] OK | 2025 Honda Amaze 1.2L I-VTEC VX CVT
[179/2070] OK | 2018 Honda BR-V 1.5L I-VTEC VX
[180/2070] OK | 2012 Honda Brio S MT
[181/2070] OK | 2012 Honda Brio V MT
[182/2070] OK | 2012 Honda Brio S MT
[183/2070] OK | 2013 Honda Brio EX MT
[184/2070] OK | 2013 Honda Brio S MT
[185/2070] OK | 2014 Honda Brio S MT
[186/2070] OK | 2015 Honda Brio S MT
[187/2070] OK | 2015 Honda Brio S MT
[188/2070] OK | 2016 Honda Brio S MT
[189/2070] OK | 2018 Honda Brio S(O) MT
[190/2070] OK | 2013 Honda City 1.5L I-VTEC S MT
[191/2070] OK | 2013 Honda City 1.5L I-VTEC S MT
[192/2070] OK | 2013 Honda City 1.5L I-VTEC S MT
[193/2070] OK | 2013 Honda City 1.5L I-VTEC V MT
[194/2070] OK | 2014 Honda City 1.5L I-VTEC V MT
[195/2070] OK | 2014 Honda City 1.5L I-VTEC V MT
[196/2070] OK | 2014 Honda City 1.5L I-VTEC SV
[197/2070] OK | 2014 Honda City 1.5L I-VTEC V MT
[198/2070] OK | 2015 Honda City 1.5L I-VTEC V MT
[199/2070] OK | 2015 Honda City 1.5L I-VTEC SV CVT
[200/2070] OK | 2015 Honda City 1.5L I-VTEC SV CVT

💾 CHECKPOINT SAVED: 200 records

[201/2070] OK | 2015 Honda City 1.5L I-VTEC SV
[202/2070] OK | 2015 Honda City 1.5L I-VTEC VX
[203/2070] OK | 2015 Honda City 1.5L I-VTEC SV CVT
[204/2070] OK | 2015 Honda City 1.5L I-VTEC VX CVT
[205/2070] OK | 2015 Honda City 1.5L I-VTEC VX CVT
[206/2070] OK | 2015 Honda City 1.5L I-VTEC SV
[207/2070] OK | 2016 Honda City 1.5L I-VTEC V MT
[208/2070] OK | 2016 Honda City 1.5L I-VTEC SV CVT
[209/2070] OK | 2016 Honda City 1.5L I-VTEC VX CVT
[210/2070] OK | 2016 Honda City 1.5L I-VTEC V MT
[211/2070] OK | 2016 Honda City 1.5L I-VTEC V MT
[212/2070] OK | 2016 Honda City 1.5L I-VTEC V MT
[213/2070] OK | 2016 Honda City 1.5L I-VTEC VX (O) MT
[214/2070] OK | 2016 Honda City 1.5L I-VTEC V MT
[215/2070] OK | 2016 Honda City 1.5L I-VTEC V MT
[216/2070] OK | 2016 Honda City 1.5L I-VTEC VX
[217/2070] OK | 2017 Honda City 1.5L I-DTEC V
[218/2070] OK | 2017 Honda City 1.5L I-VTEC ZX CVT
[219/2070] OK | 2018 Honda City 1.5L I-DTEC VX
[220/2070] OK | 2018 Honda City 1.5L I-VTEC V MT
[221/2070] OK | 2018 Honda City 1.5L I-VTE V CVT
[222/2070] OK | 2018 Honda City 1.5L I-VTEC V MT
[223/2070] OK | 2018 Honda City 1.5L I-VTEC VX CVT
[224/2070] OK | 2018 Honda City 1.5L I-VTEC ZX CVT
[225/2070] OK | 2018 Honda City 1.5L I-VTE V CVT
[226/2070] OK | 2018 Honda City 1.5L I-VTEC ZX CVT
[227/2070] OK | 2019 Honda City 1.5L I-VTEC V MT
FAILED: https://www.cars24.com/buy-used-honda-city-2019-cars-chennai-11319896120/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2019-cars-chennai-11319896120/
Call log:
  - navigating to "ht
[228/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2019-cars-mumbai-12337373135/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2019-cars-mumbai-12337373135/
Call log:
  - navigating to "htt
[229/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2019-cars-mumbai-12339492148/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2019-cars-mumbai-12339492148/
Call log:
  - navigating to "htt
[230/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2019-cars-patna-14430492118/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2019-cars-patna-14430492118/
Call log:
  - navigating to "http
[231/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2021-cars-chennai-11333568742/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2021-cars-chennai-11333568742/
Call log:
  - navigating to "ht
[232/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2021-cars-lucknow-13224876177/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2021-cars-lucknow-13224876177/
Call log:
  - navigating to "ht
[233/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2021-cars-lucknow-13260975157/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2021-cars-lucknow-13260975157/
Call log:
  - navigating to "ht
[234/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2021-cars-lucknow-13960174138/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2021-cars-lucknow-13960174138/
Call log:
  - navigating to "ht
[235/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-coimbatore-13755073137/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-coimbatore-13755073137/
Call log:
  - navigating to
[236/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-coimbatore-13797790106/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-coimbatore-13797790106/
Call log:
  - navigating to
[237/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-jaipur-10755271123/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-jaipur-10755271123/
Call log:
  - navigating to "htt
[238/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-kolkata-11931272152/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-kolkata-11931272152/
Call log:
  - navigating to "ht
[239/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-kolkata-11950977196/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-kolkata-11950977196/
Call log:
  - navigating to "ht
[240/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-kolkata-28681994167/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-kolkata-28681994167/
Call log:
  - navigating to "ht
[241/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-lucknow-13244679132/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-lucknow-13244679132/
Call log:
  - navigating to "ht
[242/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-patna-14427497100/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-patna-14427497100/
Call log:
  - navigating to "http
[243/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2022-cars-pune-10641975138/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2022-cars-pune-10641975138/
Call log:
  - navigating to "https
[244/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2023-cars-chandigarh-26253497142/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2023-cars-chandigarh-26253497142/
Call log:
  - navigating to
[245/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2024-cars-coimbatore-11397472152/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2024-cars-coimbatore-11397472152/
Call log:
  - navigating to
[246/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-city-2024-cars-patna-14485874135/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-city-2024-cars-patna-14485874135/
Call log:
  - navigating to "http
[247/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-crv-2015-cars-coimbatore-16460590109/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-crv-2015-cars-coimbatore-16460590109/
Call log:
  - navigating to "
[248/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-elevate-2023-cars-coimbatore-16403376153/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-elevate-2023-cars-coimbatore-16403376153/
Call log:
  - navigating
[249/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-elevate-2023-cars-nagpur-12359878131/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-elevate-2023-cars-nagpur-12359878131/
Call log:
  - navigating to "
[250/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-elevate-2023-cars-patna-14491770138/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-elevate-2023-cars-patna-14491770138/
Call log:
  - navigating to "h
[251/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-elevate-2024-cars-patna-14489098132/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-elevate-2024-cars-patna-14489098132/
Call log:
  - navigating to "h
[252/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-jazz-2015-cars-mohali-10934972187/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-jazz-2015-cars-mohali-10934972187/
Call log:
  - navigating to "htt
[253/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-jazz-2016-cars-chennai-22456872111/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-jazz-2016-cars-chennai-22456872111/
Call log:
  - navigating to "ht
[254/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-jazz-2017-cars-chandigarh-11634493100/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-jazz-2017-cars-chandigarh-11634493100/
Call log:
  - navigating to
[255/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-jazz-2017-cars-visakhapatnam-12242996147/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-jazz-2017-cars-visakhapatnam-12242996147/
Call log:
  - navigating
[256/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-jazz-2018-cars-bangalore-26546994161/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-jazz-2018-cars-bangalore-26546994161/
Call log:
  - navigating to "
[257/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-jazz-2018-cars-coimbatore-11390390188/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-jazz-2018-cars-coimbatore-11390390188/
Call log:
  - navigating to
[258/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-jazz-2019-cars-jaipur-10701693104/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-jazz-2019-cars-jaipur-10701693104/
Call log:
  - navigating to "htt
[259/2070] NO DATA
FAILED: https://www.cars24.com/buy-used-honda-mobilio-2015-cars-kochi-17801278183/
Reason: Page.goto: net::ERR_INTERNET_DISCONNECTED at https://www.cars24.com/buy-used-honda-mobilio-2015-cars-kochi-17801278183/
Call log:

,listing_url,car_name,brand,model,manufacturing_year,body_type,fuel_type,transmission,price_numeric,price_currency,km_driven,source_website,scraped_date
0,https://www.cars24.com/buy-used-audi-a4-2021-c...,2021 Audi A4 40 TFSI TECHNOLOGY,Audi,A4,2021,Sedan,Petrol,Automatic,2524340,INR,62836,Cars24,2026-09-21
1,https://www.cars24.com/buy-used-audi-a4-2024-c...,2024 Audi A4 40 TFSI PREMIUM PLUS,Audi,A4,2024,Sedan,Petrol,Automatic,3121340,INR,11198,Cars24,2026-09-21
2,https://www.cars24.com/buy-used-audi-a6-2014-c...,2014 Audi A6 2.0 TDI PREMIUM PLUS,Audi,A6,2014,Sedan,Diesel,Automatic,594500,INR,110048,Cars24,2026-09-21
3,https://www.cars24.com/buy-used-audi-q5-2019-c...,2019 Audi Q5 40 TDI PREMIUM PLUS,Audi,Q5,2019,SUV,Diesel,Automatic,2675340,INR,77788,Cars24,2026-09-21
4,https://www.cars24.com/buy-used-bmw-x1-2014-ca...,2014 BMW X1 SDRIVE 20D X LINE,BMW,X1,2014,SUV,Diesel,Automatic,760000,INR,99855,Cars24,2026-09-21